/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Eternal Anvil (Backend)
 * The backend server for the Eternal Anvil.
 * OpenAPI spec version: v0.0.1
 */
import { useQuery } from '@tanstack/react-query';
import type {
  QueryFunction,
  QueryKey,
  UseQueryOptions,
  UseQueryResult,
} from '@tanstack/react-query';

import type {
  Healthcheck200,
  HealthcheckErrorResponse400,
} from '../models';
import { queryInstance } from '../queryInstance';

type SecondParameter<T extends (...args: any) => any> = Parameters<T>[1];

/**
 * View that simply replies with a 'pong'.
 * @summary Healthcheck
 */
export const healthcheck = (options?: SecondParameter<typeof queryInstance>, signal?: AbortSignal) => queryInstance<Healthcheck200>(
  { url: '/ping/', method: 'GET', signal },
  options,
);

export const getHealthcheckQueryKey = () => ['/ping/'] as const;

export const getHealthcheckQueryOptions = <TData = Awaited<ReturnType<typeof healthcheck>>, TError = HealthcheckErrorResponse400>(options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof healthcheck>>, TError, TData>>, request?: SecondParameter<typeof queryInstance> },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getHealthcheckQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof healthcheck>>> = ({ signal }) => healthcheck(requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<Awaited<ReturnType<typeof healthcheck>>, TError, TData> & { queryKey: QueryKey };
};

export type HealthcheckQueryResult = NonNullable<Awaited<ReturnType<typeof healthcheck>>>;
export type HealthcheckQueryError = HealthcheckErrorResponse400;

/**
 * @summary Healthcheck
 */
export const useHealthcheck = <TData = Awaited<ReturnType<typeof healthcheck>>, TError = HealthcheckErrorResponse400>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof healthcheck>>, TError, TData>>, request?: SecondParameter<typeof queryInstance> },

): UseQueryResult<TData, TError> & { queryKey: QueryKey } => {
  const queryOptions = getHealthcheckQueryOptions(options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey;

  return query;
};
