/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Eternal Anvil (Backend)
 * The backend server for the Eternal Anvil.
 * OpenAPI spec version: v0.0.1
 */
import { useQuery } from '@tanstack/react-query';
import type {
  QueryFunction,
  QueryKey,
  UseQueryOptions,
  UseQueryResult,
} from '@tanstack/react-query';

import type {
  PingRetrieve200,
  PingRetrieveErrorResponse400,
} from '../../models';
import { queryInstance } from '../../queryInstance';

type SecondParameter<T extends (...args: any) => any> = Parameters<T>[1];

/**
 * View that simply replies with a 'pong'.
 */
export const pingRetrieve = (options?: SecondParameter<typeof queryInstance>, signal?: AbortSignal) => queryInstance<PingRetrieve200>(
  { url: '/ping/', method: 'GET', signal },
  options,
);

export const getPingRetrieveQueryKey = () => ['/ping/'] as const;

export const getPingRetrieveQueryOptions = <TData = Awaited<ReturnType<typeof pingRetrieve>>, TError = PingRetrieveErrorResponse400>(options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof pingRetrieve>>, TError, TData>>, request?: SecondParameter<typeof queryInstance> },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getPingRetrieveQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof pingRetrieve>>> = ({ signal }) => pingRetrieve(requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<Awaited<ReturnType<typeof pingRetrieve>>, TError, TData> & { queryKey: QueryKey };
};

export type PingRetrieveQueryResult = NonNullable<Awaited<ReturnType<typeof pingRetrieve>>>;
export type PingRetrieveQueryError = PingRetrieveErrorResponse400;

export const usePingRetrieve = <TData = Awaited<ReturnType<typeof pingRetrieve>>, TError = PingRetrieveErrorResponse400>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof pingRetrieve>>, TError, TData>>, request?: SecondParameter<typeof queryInstance> },

): UseQueryResult<TData, TError> & { queryKey: QueryKey } => {
  const queryOptions = getPingRetrieveQueryOptions(options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey;

  return query;
};
