/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Eternal Anvil (Backend)
 * The backend server for the Eternal Anvil.
 * OpenAPI spec version: v0.0.1
 */

/**
 * * `client_error` - Client Error
 */
export type ClientErrorEnum = typeof ClientErrorEnum[keyof typeof ClientErrorEnum];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ClientErrorEnum = {
  client_error: 'client_error',
} as const;
