/**
 * Generated by orval v7.0.1 🍺
 * Do not edit manually.
 * Eternal Anvil (Backend)
 * The backend server for the Eternal Anvil.
 * OpenAPI spec version: v0.0.1
 */
import type { ClientErrorEnum } from './clientErrorEnum';
import type { Error404 } from './error404';

export interface ErrorResponse404 {
  errors: Error404[];
  type: ClientErrorEnum;
}
