/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Eternal Anvil (Backend)
 * The backend server for the Eternal Anvil.
 * OpenAPI spec version: v0.0.1
 */

/**
 * * `not_found` - Not Found
 */
export type ErrorCode404Enum = typeof ErrorCode404Enum[keyof typeof ErrorCode404Enum];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ErrorCode404Enum = {
  not_found: 'not_found',
} as const;
