/**
 * Generated by orval v7.0.1 🍺
 * Do not edit manually.
 * Eternal Anvil (Backend)
 * The backend server for the Eternal Anvil.
 * OpenAPI spec version: v0.0.1
 */

export interface GameWorldRequest {
  /**
   * @minLength 1
   * @maxLength 255
   */
  code: string;
  /**
   * @minLength 1
   * @maxLength 255
   */
  name: string;
}
