/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Eternal Anvil (Backend)
 * The backend server for the Eternal Anvil.
 * OpenAPI spec version: v0.0.1
 */
import type { EconomyEnum } from './economyEnum';
import type { GameWorld } from './gameWorld';
import type { ListCreateAccountRealm } from './listCreateAccountRealm';
import type { RaceEnum } from './raceEnum';
import type { User } from './user';

export interface ListCreateAccount {
  economy: EconomyEnum;
  game_world: GameWorld;
  readonly id: string;
  /** @maxLength 255 */
  name: string;
  readonly players: readonly User[];
  race: RaceEnum;
  /** @nullable */
  readonly realm: ListCreateAccountRealm;
}
