/**
 * Generated by orval v7.0.1 🍺
 * Do not edit manually.
 * Eternal Anvil (Backend)
 * The backend server for the Eternal Anvil.
 * OpenAPI spec version: v0.0.1
 */

export interface ListGameWorld {
  /** @nullable */
  readonly account_name: string | null;
  /** @maxLength 255 */
  code: string;
  end: string;
  readonly id: string;
  /** @maxLength 255 */
  name: string;
  start: string;
}
