/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Eternal Anvil (Backend)
 * The backend server for the Eternal Anvil.
 * OpenAPI spec version: v0.0.1
 */
import type { EconomyEnum } from './economyEnum';
import type { RaceEnum } from './raceEnum';

export interface ListCreateAccount {
  economy: EconomyEnum;
  game_world: string;
  readonly id: string;
  /** @maxLength 255 */
  name: string;
  race: RaceEnum;
}
