/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Eternal Anvil (Backend)
 * The backend server for the Eternal Anvil.
 * OpenAPI spec version: v0.0.1
 */

/**
 * * `parse_error` - Parse Error
 */
export type ParseErrorCodeEnum = typeof ParseErrorCodeEnum[keyof typeof ParseErrorCodeEnum];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ParseErrorCodeEnum = {
  parse_error: 'parse_error',
} as const;
