/**
 * Generated by orval v7.0.1 🍺
 * Do not edit manually.
 * Eternal Anvil (Backend)
 * The backend server for the Eternal Anvil.
 * OpenAPI spec version: v0.0.1
 */
import type { ParseErrorCodeEnum } from './parseErrorCodeEnum';

export interface ParseError {
  /** @nullable */
  attr: string | null;
  code: ParseErrorCodeEnum;
  detail: string;
}
