/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Eternal Anvil (Backend)
 * The backend server for the Eternal Anvil.
 * OpenAPI spec version: v0.0.1
 */
import type { CodeEnum } from './codeEnum';

export interface ParseError {
  /** @nullable */
  attr: string | null;
  code: CodeEnum;
  detail: string;
}
