/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Eternal Anvil (Backend)
 * The backend server for the Eternal Anvil.
 * OpenAPI spec version: v0.0.1
 */

/**
 * Serializer to handle user's details.
 */
export interface PatchedUserProfile {
  /** @maxLength 255 */
  username?: string;
}
