/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Eternal Anvil (Backend)
 * The backend server for the Eternal Anvil.
 * OpenAPI spec version: v0.0.1
 */

export type PingRetrieve200 = typeof PingRetrieve200[keyof typeof PingRetrieve200];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PingRetrieve200 = {
  pong: 'pong',
} as const;
