/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Eternal Anvil (Backend)
 * The backend server for the Eternal Anvil.
 * OpenAPI spec version: v0.0.1
 */

export type RealmManagerAccountsJoinCreate403ErrorsItemAttr = typeof RealmManagerAccountsJoinCreate403ErrorsItemAttr[keyof typeof RealmManagerAccountsJoinCreate403ErrorsItemAttr];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const RealmManagerAccountsJoinCreate403ErrorsItemAttr = {
  user: 'user',
} as const;
