/**
 * Generated by orval v7.0.1 🍺
 * Do not edit manually.
 * Eternal Anvil (Backend)
 * The backend server for the Eternal Anvil.
 * OpenAPI spec version: v0.0.1
 */

/**
 * * `invalid` - invalid
* `max_string_length` - max_string_length
* `max_value` - max_value
* `min_value` - min_value
* `null` - null
* `required` - required
 */
export type RealmManagerAccountsSchedulePartialUpdateWednesdayINDEXErrorComponentCode = typeof RealmManagerAccountsSchedulePartialUpdateWednesdayINDEXErrorComponentCode[keyof typeof RealmManagerAccountsSchedulePartialUpdateWednesdayINDEXErrorComponentCode];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const RealmManagerAccountsSchedulePartialUpdateWednesdayINDEXErrorComponentCode = {
  invalid: 'invalid',
  max_string_length: 'max_string_length',
  max_value: 'max_value',
  min_value: 'min_value',
  null: 'null',
  required: 'required',
} as const;
