/**
 * Generated by orval v7.0.1 🍺
 * Do not edit manually.
 * Eternal Anvil (Backend)
 * The backend server for the Eternal Anvil.
 * OpenAPI spec version: v0.0.1
 */
import type { RealmManagerAccountsCreate403ErrorsItemAttr } from './realmManagerAccountsCreate403ErrorsItemAttr';
import type { RealmManagerAccountsCreate403ErrorsItemCode } from './realmManagerAccountsCreate403ErrorsItemCode';
import type { RealmManagerAccountsCreate403ErrorsItemDetail } from './realmManagerAccountsCreate403ErrorsItemDetail';

export type RealmManagerAccountsCreate403ErrorsItem = {
  attr: RealmManagerAccountsCreate403ErrorsItemAttr;
  code: RealmManagerAccountsCreate403ErrorsItemCode;
  detail: RealmManagerAccountsCreate403ErrorsItemDetail;
};
