/**
 * Generated by orval v7.0.1 🍺
 * Do not edit manually.
 * Eternal Anvil (Backend)
 * The backend server for the Eternal Anvil.
 * OpenAPI spec version: v0.0.1
 */
import type { ParseErrorResponse } from './parseErrorResponse';
import type { RealmManagerAccountsUpdateValidationError } from './realmManagerAccountsUpdateValidationError';

export type RealmManagerAccountsUpdateErrorResponse400 = RealmManagerAccountsUpdateValidationError | ParseErrorResponse;
