/**
 * Generated by orval v7.0.1 🍺
 * Do not edit manually.
 * Eternal Anvil (Backend)
 * The backend server for the Eternal Anvil.
 * OpenAPI spec version: v0.0.1
 */
import type { RealmManagerAccountsUpdateError } from './realmManagerAccountsUpdateError';
import type { RealmManagerAccountsUpdateValidationErrorType } from './realmManagerAccountsUpdateValidationErrorType';

export interface RealmManagerAccountsUpdateValidationError {
  errors: RealmManagerAccountsUpdateError[];
  type: RealmManagerAccountsUpdateValidationErrorType;
}
