/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Eternal Anvil (Backend)
 * The backend server for the Eternal Anvil.
 * OpenAPI spec version: v0.0.1
 */
import type { RealmManagerAccountsJoinCreateIdErrorComponentAttr } from './realmManagerAccountsJoinCreateIdErrorComponentAttr';
import type { RealmManagerAccountsJoinCreateIdErrorComponentCode } from './realmManagerAccountsJoinCreateIdErrorComponentCode';

export interface RealmManagerAccountsJoinCreateIdErrorComponent {
  attr: RealmManagerAccountsJoinCreateIdErrorComponentAttr;
  /** * `invalid` - invalid
* `null` - null
* `required` - required */
  code: RealmManagerAccountsJoinCreateIdErrorComponentCode;
  detail: string;
}
