/**
 * Generated by orval v7.0.1 🍺
 * Do not edit manually.
 * Eternal Anvil (Backend)
 * The backend server for the Eternal Anvil.
 * OpenAPI spec version: v0.0.1
 */
import type { RealmManagerAccountsCreateError } from './realmManagerAccountsCreateError';
import type { RealmManagerAccountsCreateValidationErrorType } from './realmManagerAccountsCreateValidationErrorType';

export interface RealmManagerAccountsCreateValidationError {
  errors: RealmManagerAccountsCreateError[];
  type: RealmManagerAccountsCreateValidationErrorType;
}
