/**
 * Generated by orval v7.0.1 🍺
 * Do not edit manually.
 * Eternal Anvil (Backend)
 * The backend server for the Eternal Anvil.
 * OpenAPI spec version: v0.0.1
 */
import type { RealmManagerAccountsSchedulePartialUpdateWednesdayErrorComponentAttr } from './realmManagerAccountsSchedulePartialUpdateWednesdayErrorComponentAttr';
import type { RealmManagerAccountsSchedulePartialUpdateWednesdayErrorComponentCode } from './realmManagerAccountsSchedulePartialUpdateWednesdayErrorComponentCode';

export interface RealmManagerAccountsSchedulePartialUpdateWednesdayErrorComponent {
  attr: RealmManagerAccountsSchedulePartialUpdateWednesdayErrorComponentAttr;
  /** * `not_a_list` - not_a_list
* `null` - null */
  code: RealmManagerAccountsSchedulePartialUpdateWednesdayErrorComponentCode;
  detail: string;
}
