/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Eternal Anvil (Backend)
 * The backend server for the Eternal Anvil.
 * OpenAPI spec version: v0.0.1
 */

export type RealmManagerAccountsLeave403ErrorsItemDetail = typeof RealmManagerAccountsLeave403ErrorsItemDetail[keyof typeof RealmManagerAccountsLeave403ErrorsItemDetail];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const RealmManagerAccountsLeave403ErrorsItemDetail = {
  The_owner_of_the_account_cannot_be_removed: 'The owner of the account cannot be removed.',
} as const;
