/**
 * Generated by orval v7.0.1 🍺
 * Do not edit manually.
 * Eternal Anvil (Backend)
 * The backend server for the Eternal Anvil.
 * OpenAPI spec version: v0.0.1
 */
import type { RealmManagerAccountsSchedulePartialUpdateMondayErrorComponentAttr } from './realmManagerAccountsSchedulePartialUpdateMondayErrorComponentAttr';
import type { RealmManagerAccountsSchedulePartialUpdateMondayErrorComponentCode } from './realmManagerAccountsSchedulePartialUpdateMondayErrorComponentCode';

export interface RealmManagerAccountsSchedulePartialUpdateMondayErrorComponent {
  attr: RealmManagerAccountsSchedulePartialUpdateMondayErrorComponentAttr;
  /** * `not_a_list` - not_a_list
* `null` - null */
  code: RealmManagerAccountsSchedulePartialUpdateMondayErrorComponentCode;
  detail: string;
}
