/**
 * Generated by orval v7.0.1 🍺
 * Do not edit manually.
 * Eternal Anvil (Backend)
 * The backend server for the Eternal Anvil.
 * OpenAPI spec version: v0.0.1
 */

export type RealmManagerAccountsCreate403ErrorsItemAttr = typeof RealmManagerAccountsCreate403ErrorsItemAttr[keyof typeof RealmManagerAccountsCreate403ErrorsItemAttr];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const RealmManagerAccountsCreate403ErrorsItemAttr = {
  user: 'user',
} as const;
