/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Eternal Anvil (Backend)
 * The backend server for the Eternal Anvil.
 * OpenAPI spec version: v0.0.1
 */

export type RealmManagerAccountsJoinCreate403ErrorsItemCode = typeof RealmManagerAccountsJoinCreate403ErrorsItemCode[keyof typeof RealmManagerAccountsJoinCreate403ErrorsItemCode];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const RealmManagerAccountsJoinCreate403ErrorsItemCode = {
  multi_account: 'multi_account',
} as const;
