/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Eternal Anvil (Backend)
 * The backend server for the Eternal Anvil.
 * OpenAPI spec version: v0.0.1
 */

export type RealmManagerAccountsCreate403ErrorsItemCode = typeof RealmManagerAccountsCreate403ErrorsItemCode[keyof typeof RealmManagerAccountsCreate403ErrorsItemCode];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const RealmManagerAccountsCreate403ErrorsItemCode = {
  multi_account: 'multi_account',
} as const;
