/**
 * Generated by orval v7.0.1 🍺
 * Do not edit manually.
 * Eternal Anvil (Backend)
 * The backend server for the Eternal Anvil.
 * OpenAPI spec version: v0.0.1
 */
import type { RealmManagerAccountsCreateNonFieldErrorsErrorComponentAttr } from './realmManagerAccountsCreateNonFieldErrorsErrorComponentAttr';
import type { RealmManagerAccountsCreateNonFieldErrorsErrorComponentCode } from './realmManagerAccountsCreateNonFieldErrorsErrorComponentCode';

export interface RealmManagerAccountsCreateNonFieldErrorsErrorComponent {
  attr: RealmManagerAccountsCreateNonFieldErrorsErrorComponentAttr;
  /** * `invalid` - invalid
* `null` - null */
  code: RealmManagerAccountsCreateNonFieldErrorsErrorComponentCode;
  detail: string;
}
