/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Eternal Anvil (Backend)
 * The backend server for the Eternal Anvil.
 * OpenAPI spec version: v0.0.1
 */
import type { RealmManagerAccountsLeave403ErrorsItem } from './realmManagerAccountsLeave403ErrorsItem';
import type { RealmManagerAccountsLeave403Type } from './realmManagerAccountsLeave403Type';

export type RealmManagerAccountsLeave403 = {
  errors: RealmManagerAccountsLeave403ErrorsItem[];
  type: RealmManagerAccountsLeave403Type;
};
