/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Eternal Anvil (Backend)
 * The backend server for the Eternal Anvil.
 * OpenAPI spec version: v0.0.1
 */

export type RealmManagerAccountsJoin403Type = typeof RealmManagerAccountsJoin403Type[keyof typeof RealmManagerAccountsJoin403Type];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const RealmManagerAccountsJoin403Type = {
  validation_error: 'validation_error',
} as const;
