/**
 * Generated by orval v7.0.1 🍺
 * Do not edit manually.
 * Eternal Anvil (Backend)
 * The backend server for the Eternal Anvil.
 * OpenAPI spec version: v0.0.1
 */

export type RealmManagerAccountsScheduleUpdateThursdayINDEXErrorComponentAttr = typeof RealmManagerAccountsScheduleUpdateThursdayINDEXErrorComponentAttr[keyof typeof RealmManagerAccountsScheduleUpdateThursdayINDEXErrorComponentAttr];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const RealmManagerAccountsScheduleUpdateThursdayINDEXErrorComponentAttr = {
  thursdayINDEX: 'thursday.INDEX',
} as const;
