/**
 * Generated by orval v7.0.1 🍺
 * Do not edit manually.
 * Eternal Anvil (Backend)
 * The backend server for the Eternal Anvil.
 * OpenAPI spec version: v0.0.1
 */

export type RealmManagerAccountsSchedulePartialUpdateThursdayErrorComponentAttr = typeof RealmManagerAccountsSchedulePartialUpdateThursdayErrorComponentAttr[keyof typeof RealmManagerAccountsSchedulePartialUpdateThursdayErrorComponentAttr];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const RealmManagerAccountsSchedulePartialUpdateThursdayErrorComponentAttr = {
  thursday: 'thursday',
} as const;
