/**
 * Generated by orval v7.0.1 🍺
 * Do not edit manually.
 * Eternal Anvil (Backend)
 * The backend server for the Eternal Anvil.
 * OpenAPI spec version: v0.0.1
 */

export type RealmManagerAccountsScheduleUpdateFridayErrorComponentAttr = typeof RealmManagerAccountsScheduleUpdateFridayErrorComponentAttr[keyof typeof RealmManagerAccountsScheduleUpdateFridayErrorComponentAttr];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const RealmManagerAccountsScheduleUpdateFridayErrorComponentAttr = {
  friday: 'friday',
} as const;
