/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Eternal Anvil (Backend)
 * The backend server for the Eternal Anvil.
 * OpenAPI spec version: v0.0.1
 */
import type { RealmManagerAccountsCreateError } from './realmManagerAccountsCreateError';
import type { RealmManagerAccountsCreateValidationErrorType } from './realmManagerAccountsCreateValidationErrorType';

export interface RealmManagerAccountsCreateValidationError {
  errors: RealmManagerAccountsCreateError[];
  type: RealmManagerAccountsCreateValidationErrorType;
}
