/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Eternal Anvil (Backend)
 * The backend server for the Eternal Anvil.
 * OpenAPI spec version: v0.0.1
 */

export type RealmManagerAccountsJoin403ErrorsItemDetail = typeof RealmManagerAccountsJoin403ErrorsItemDetail[keyof typeof RealmManagerAccountsJoin403ErrorsItemDetail];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const RealmManagerAccountsJoin403ErrorsItemDetail = {
  User_is_already_present_in_this_game_world: 'User is already present in this game world.',
} as const;
