/**
 * Generated by orval v7.0.1 🍺
 * Do not edit manually.
 * Eternal Anvil (Backend)
 * The backend server for the Eternal Anvil.
 * OpenAPI spec version: v0.0.1
 */

export type RealmManagerAccountsJoinIdErrorComponentAttr = typeof RealmManagerAccountsJoinIdErrorComponentAttr[keyof typeof RealmManagerAccountsJoinIdErrorComponentAttr];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const RealmManagerAccountsJoinIdErrorComponentAttr = {
  id: 'id',
} as const;
