/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Eternal Anvil (Backend)
 * The backend server for the Eternal Anvil.
 * OpenAPI spec version: v0.0.1
 */

export type RealmManagerAccountsLeave403ErrorsItemCode = typeof RealmManagerAccountsLeave403ErrorsItemCode[keyof typeof RealmManagerAccountsLeave403ErrorsItemCode];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const RealmManagerAccountsLeave403ErrorsItemCode = {
  failed_remove_owner: 'failed_remove_owner',
} as const;
