/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Eternal Anvil (Backend)
 * The backend server for the Eternal Anvil.
 * OpenAPI spec version: v0.0.1
 */
import type { RealmManagerAccountsUpdateNonFieldErrorsErrorComponent } from './realmManagerAccountsUpdateNonFieldErrorsErrorComponent';
import type { RealmManagerAccountsUpdateOwnerErrorComponent } from './realmManagerAccountsUpdateOwnerErrorComponent';

export type RealmManagerAccountsUpdateError = RealmManagerAccountsUpdateNonFieldErrorsErrorComponent | RealmManagerAccountsUpdateOwnerErrorComponent;
