/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Eternal Anvil (Backend)
 * The backend server for the Eternal Anvil.
 * OpenAPI spec version: v0.0.1
 */
import type { RealmManagerAccountsDestroy403ErrorsItemAttr } from './realmManagerAccountsDestroy403ErrorsItemAttr';
import type { RealmManagerAccountsDestroy403ErrorsItemCode } from './realmManagerAccountsDestroy403ErrorsItemCode';
import type { RealmManagerAccountsDestroy403ErrorsItemDetail } from './realmManagerAccountsDestroy403ErrorsItemDetail';

export type RealmManagerAccountsDestroy403ErrorsItem = {
  attr: RealmManagerAccountsDestroy403ErrorsItemAttr;
  code: RealmManagerAccountsDestroy403ErrorsItemCode;
  detail: RealmManagerAccountsDestroy403ErrorsItemDetail;
};
