/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Eternal Anvil (Backend)
 * The backend server for the Eternal Anvil.
 * OpenAPI spec version: v0.0.1
 */
import type { RealmManagerAccountsLeave403ErrorsItemAttr } from './realmManagerAccountsLeave403ErrorsItemAttr';
import type { RealmManagerAccountsLeave403ErrorsItemCode } from './realmManagerAccountsLeave403ErrorsItemCode';
import type { RealmManagerAccountsLeave403ErrorsItemDetail } from './realmManagerAccountsLeave403ErrorsItemDetail';

export type RealmManagerAccountsLeave403ErrorsItem = {
  attr: RealmManagerAccountsLeave403ErrorsItemAttr;
  code: RealmManagerAccountsLeave403ErrorsItemCode;
  detail: RealmManagerAccountsLeave403ErrorsItemDetail;
};
