/**
 * Generated by orval v7.0.1 🍺
 * Do not edit manually.
 * Eternal Anvil (Backend)
 * The backend server for the Eternal Anvil.
 * OpenAPI spec version: v0.0.1
 */
import type { RealmManagerAccountsScheduleUpdateSundayErrorComponentAttr } from './realmManagerAccountsScheduleUpdateSundayErrorComponentAttr';
import type { RealmManagerAccountsScheduleUpdateSundayErrorComponentCode } from './realmManagerAccountsScheduleUpdateSundayErrorComponentCode';

export interface RealmManagerAccountsScheduleUpdateSundayErrorComponent {
  attr: RealmManagerAccountsScheduleUpdateSundayErrorComponentAttr;
  /** * `not_a_list` - not_a_list
* `null` - null */
  code: RealmManagerAccountsScheduleUpdateSundayErrorComponentCode;
  detail: string;
}
