/**
 * Generated by orval v7.0.1 🍺
 * Do not edit manually.
 * Eternal Anvil (Backend)
 * The backend server for the Eternal Anvil.
 * OpenAPI spec version: v0.0.1
 */
import type { RealmManagerAccountsSchedulePartialUpdateThursdayINDEXErrorComponentAttr } from './realmManagerAccountsSchedulePartialUpdateThursdayINDEXErrorComponentAttr';
import type { RealmManagerAccountsSchedulePartialUpdateThursdayINDEXErrorComponentCode } from './realmManagerAccountsSchedulePartialUpdateThursdayINDEXErrorComponentCode';

export interface RealmManagerAccountsSchedulePartialUpdateThursdayINDEXErrorComponent {
  attr: RealmManagerAccountsSchedulePartialUpdateThursdayINDEXErrorComponentAttr;
  /** * `invalid` - invalid
* `max_string_length` - max_string_length
* `max_value` - max_value
* `min_value` - min_value
* `null` - null
* `required` - required */
  code: RealmManagerAccountsSchedulePartialUpdateThursdayINDEXErrorComponentCode;
  detail: string;
}
