/**
 * Generated by orval v7.0.1 🍺
 * Do not edit manually.
 * Eternal Anvil (Backend)
 * The backend server for the Eternal Anvil.
 * OpenAPI spec version: v0.0.1
 */
import type { RealmManagerAccountsCreate403ErrorsItem } from './realmManagerAccountsCreate403ErrorsItem';
import type { RealmManagerAccountsCreate403Type } from './realmManagerAccountsCreate403Type';

export type RealmManagerAccountsCreate403 = {
  errors: RealmManagerAccountsCreate403ErrorsItem[];
  type: RealmManagerAccountsCreate403Type;
};
