/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Eternal Anvil (Backend)
 * The backend server for the Eternal Anvil.
 * OpenAPI spec version: v0.0.1
 */
import type { RealmManagerAccountsCreateRaceErrorComponentAttr } from './realmManagerAccountsCreateRaceErrorComponentAttr';
import type { RealmManagerAccountsCreateRaceErrorComponentCode } from './realmManagerAccountsCreateRaceErrorComponentCode';

export interface RealmManagerAccountsCreateRaceErrorComponent {
  attr: RealmManagerAccountsCreateRaceErrorComponentAttr;
  /** * `invalid_choice` - invalid_choice
* `null` - null
* `required` - required */
  code: RealmManagerAccountsCreateRaceErrorComponentCode;
  detail: string;
}
