/**
 * Generated by orval v7.0.1 🍺
 * Do not edit manually.
 * Eternal Anvil (Backend)
 * The backend server for the Eternal Anvil.
 * OpenAPI spec version: v0.0.1
 */
import type { RealmManagerAccountsScheduleUpdateThursdayErrorComponentAttr } from './realmManagerAccountsScheduleUpdateThursdayErrorComponentAttr';
import type { RealmManagerAccountsScheduleUpdateThursdayErrorComponentCode } from './realmManagerAccountsScheduleUpdateThursdayErrorComponentCode';

export interface RealmManagerAccountsScheduleUpdateThursdayErrorComponent {
  attr: RealmManagerAccountsScheduleUpdateThursdayErrorComponentAttr;
  /** * `not_a_list` - not_a_list
* `null` - null */
  code: RealmManagerAccountsScheduleUpdateThursdayErrorComponentCode;
  detail: string;
}
