/**
 * Generated by orval v7.0.1 🍺
 * Do not edit manually.
 * Eternal Anvil (Backend)
 * The backend server for the Eternal Anvil.
 * OpenAPI spec version: v0.0.1
 */

export type RealmManagerAccountsScheduleUpdateThursdayErrorComponentAttr = typeof RealmManagerAccountsScheduleUpdateThursdayErrorComponentAttr[keyof typeof RealmManagerAccountsScheduleUpdateThursdayErrorComponentAttr];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const RealmManagerAccountsScheduleUpdateThursdayErrorComponentAttr = {
  thursday: 'thursday',
} as const;
