/**
 * Generated by orval v7.0.1 🍺
 * Do not edit manually.
 * Eternal Anvil (Backend)
 * The backend server for the Eternal Anvil.
 * OpenAPI spec version: v0.0.1
 */
import type { RealmManagerAccountsScheduleUpdateWednesdayErrorComponentAttr } from './realmManagerAccountsScheduleUpdateWednesdayErrorComponentAttr';
import type { RealmManagerAccountsScheduleUpdateWednesdayErrorComponentCode } from './realmManagerAccountsScheduleUpdateWednesdayErrorComponentCode';

export interface RealmManagerAccountsScheduleUpdateWednesdayErrorComponent {
  attr: RealmManagerAccountsScheduleUpdateWednesdayErrorComponentAttr;
  /** * `not_a_list` - not_a_list
* `null` - null */
  code: RealmManagerAccountsScheduleUpdateWednesdayErrorComponentCode;
  detail: string;
}
