/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Eternal Anvil (Backend)
 * The backend server for the Eternal Anvil.
 * OpenAPI spec version: v0.0.1
 */
import type { RealmManagerAccountsCreateEconomyErrorComponent } from './realmManagerAccountsCreateEconomyErrorComponent';
import type { RealmManagerAccountsCreateGameWorldErrorComponent } from './realmManagerAccountsCreateGameWorldErrorComponent';
import type { RealmManagerAccountsCreateNameErrorComponent } from './realmManagerAccountsCreateNameErrorComponent';
import type { RealmManagerAccountsCreateNonFieldErrorsErrorComponent } from './realmManagerAccountsCreateNonFieldErrorsErrorComponent';
import type { RealmManagerAccountsCreateRaceErrorComponent } from './realmManagerAccountsCreateRaceErrorComponent';

export type RealmManagerAccountsCreateError = RealmManagerAccountsCreateNonFieldErrorsErrorComponent | RealmManagerAccountsCreateNameErrorComponent | RealmManagerAccountsCreateGameWorldErrorComponent | RealmManagerAccountsCreateRaceErrorComponent | RealmManagerAccountsCreateEconomyErrorComponent;
