/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Eternal Anvil (Backend)
 * The backend server for the Eternal Anvil.
 * OpenAPI spec version: v0.0.1
 */
import type { RealmManagerAccountsJoinCreate403ErrorsItem } from './realmManagerAccountsJoinCreate403ErrorsItem';
import type { RealmManagerAccountsJoinCreate403Type } from './realmManagerAccountsJoinCreate403Type';

export type RealmManagerAccountsJoinCreate403 = {
  errors: RealmManagerAccountsJoinCreate403ErrorsItem[];
  type: RealmManagerAccountsJoinCreate403Type;
};
