/**
 * Generated by orval v7.0.1 🍺
 * Do not edit manually.
 * Eternal Anvil (Backend)
 * The backend server for the Eternal Anvil.
 * OpenAPI spec version: v0.0.1
 */

export type RealmManagerAccountsRemoveUser403ErrorsItemCode = typeof RealmManagerAccountsRemoveUser403ErrorsItemCode[keyof typeof RealmManagerAccountsRemoveUser403ErrorsItemCode];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const RealmManagerAccountsRemoveUser403ErrorsItemCode = {
  permission_denied: 'permission_denied',
} as const;
