/**
 * Generated by orval v7.0.1 🍺
 * Do not edit manually.
 * Eternal Anvil (Backend)
 * The backend server for the Eternal Anvil.
 * OpenAPI spec version: v0.0.1
 */
import type { RealmManagerAccountsScheduleUpdateSaturdayErrorComponentAttr } from './realmManagerAccountsScheduleUpdateSaturdayErrorComponentAttr';
import type { RealmManagerAccountsScheduleUpdateSaturdayErrorComponentCode } from './realmManagerAccountsScheduleUpdateSaturdayErrorComponentCode';

export interface RealmManagerAccountsScheduleUpdateSaturdayErrorComponent {
  attr: RealmManagerAccountsScheduleUpdateSaturdayErrorComponentAttr;
  /** * `not_a_list` - not_a_list
* `null` - null */
  code: RealmManagerAccountsScheduleUpdateSaturdayErrorComponentCode;
  detail: string;
}
