/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Eternal Anvil (Backend)
 * The backend server for the Eternal Anvil.
 * OpenAPI spec version: v0.0.1
 */
import type { RealmManagerAccountsJoin403ErrorsItemAttr } from './realmManagerAccountsJoin403ErrorsItemAttr';
import type { RealmManagerAccountsJoin403ErrorsItemCode } from './realmManagerAccountsJoin403ErrorsItemCode';
import type { RealmManagerAccountsJoin403ErrorsItemDetail } from './realmManagerAccountsJoin403ErrorsItemDetail';

export type RealmManagerAccountsJoin403ErrorsItem = {
  attr: RealmManagerAccountsJoin403ErrorsItemAttr;
  code: RealmManagerAccountsJoin403ErrorsItemCode;
  detail: RealmManagerAccountsJoin403ErrorsItemDetail;
};
