/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Eternal Anvil (Backend)
 * The backend server for the Eternal Anvil.
 * OpenAPI spec version: v0.0.1
 */
import type { RealmManagerAccountsCreateEconomyErrorComponentAttr } from './realmManagerAccountsCreateEconomyErrorComponentAttr';
import type { RealmManagerAccountsCreateEconomyErrorComponentCode } from './realmManagerAccountsCreateEconomyErrorComponentCode';

export interface RealmManagerAccountsCreateEconomyErrorComponent {
  attr: RealmManagerAccountsCreateEconomyErrorComponentAttr;
  /** * `invalid_choice` - invalid_choice
* `null` - null
* `required` - required */
  code: RealmManagerAccountsCreateEconomyErrorComponentCode;
  detail: string;
}
