/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Eternal Anvil (Backend)
 * The backend server for the Eternal Anvil.
 * OpenAPI spec version: v0.0.1
 */

export type RealmManagerAccountsUpdate403ErrorsItemAttr = typeof RealmManagerAccountsUpdate403ErrorsItemAttr[keyof typeof RealmManagerAccountsUpdate403ErrorsItemAttr];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const RealmManagerAccountsUpdate403ErrorsItemAttr = {
  user: 'user',
} as const;
