/**
 * Generated by orval v7.0.1 🍺
 * Do not edit manually.
 * Eternal Anvil (Backend)
 * The backend server for the Eternal Anvil.
 * OpenAPI spec version: v0.0.1
 */

export type RealmManagerAccountsScheduleUpdateNonFieldErrorsErrorComponentAttr = typeof RealmManagerAccountsScheduleUpdateNonFieldErrorsErrorComponentAttr[keyof typeof RealmManagerAccountsScheduleUpdateNonFieldErrorsErrorComponentAttr];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const RealmManagerAccountsScheduleUpdateNonFieldErrorsErrorComponentAttr = {
  non_field_errors: 'non_field_errors',
} as const;
