/**
 * Generated by orval v7.0.1 🍺
 * Do not edit manually.
 * Eternal Anvil (Backend)
 * The backend server for the Eternal Anvil.
 * OpenAPI spec version: v0.0.1
 */

export type RealmManagerAccountsScheduleUpdateWednesdayErrorComponentAttr = typeof RealmManagerAccountsScheduleUpdateWednesdayErrorComponentAttr[keyof typeof RealmManagerAccountsScheduleUpdateWednesdayErrorComponentAttr];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const RealmManagerAccountsScheduleUpdateWednesdayErrorComponentAttr = {
  wednesday: 'wednesday',
} as const;
