/**
 * Generated by orval v7.0.1 🍺
 * Do not edit manually.
 * Eternal Anvil (Backend)
 * The backend server for the Eternal Anvil.
 * OpenAPI spec version: v0.0.1
 */
import type { RealmManagerAccountsScheduleUpdateMondayErrorComponentAttr } from './realmManagerAccountsScheduleUpdateMondayErrorComponentAttr';
import type { RealmManagerAccountsScheduleUpdateMondayErrorComponentCode } from './realmManagerAccountsScheduleUpdateMondayErrorComponentCode';

export interface RealmManagerAccountsScheduleUpdateMondayErrorComponent {
  attr: RealmManagerAccountsScheduleUpdateMondayErrorComponentAttr;
  /** * `not_a_list` - not_a_list
* `null` - null */
  code: RealmManagerAccountsScheduleUpdateMondayErrorComponentCode;
  detail: string;
}
