/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Eternal Anvil (Backend)
 * The backend server for the Eternal Anvil.
 * OpenAPI spec version: v0.0.1
 */
import type { RealmManagerAccountsUpdate403ErrorsItem } from './realmManagerAccountsUpdate403ErrorsItem';
import type { RealmManagerAccountsUpdate403Type } from './realmManagerAccountsUpdate403Type';

export type RealmManagerAccountsUpdate403 = {
  errors: RealmManagerAccountsUpdate403ErrorsItem[];
  type: RealmManagerAccountsUpdate403Type;
};
