/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Eternal Anvil (Backend)
 * The backend server for the Eternal Anvil.
 * OpenAPI spec version: v0.0.1
 */

/**
 * * `does_not_exist` - does_not_exist
* `incorrect_type` - incorrect_type
* `null` - null
* `required` - required
 */
export type RealmManagerAccountsCreateGameWorldErrorComponentCode = typeof RealmManagerAccountsCreateGameWorldErrorComponentCode[keyof typeof RealmManagerAccountsCreateGameWorldErrorComponentCode];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const RealmManagerAccountsCreateGameWorldErrorComponentCode = {
  does_not_exist: 'does_not_exist',
  incorrect_type: 'incorrect_type',
  null: 'null',
  required: 'required',
} as const;
