/**
 * Generated by orval v7.0.1 🍺
 * Do not edit manually.
 * Eternal Anvil (Backend)
 * The backend server for the Eternal Anvil.
 * OpenAPI spec version: v0.0.1
 */

export type RealmManagerAccountsSchedulePartialUpdateFridayINDEXErrorComponentAttr = typeof RealmManagerAccountsSchedulePartialUpdateFridayINDEXErrorComponentAttr[keyof typeof RealmManagerAccountsSchedulePartialUpdateFridayINDEXErrorComponentAttr];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const RealmManagerAccountsSchedulePartialUpdateFridayINDEXErrorComponentAttr = {
  fridayINDEX: 'friday.INDEX',
} as const;
