/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Eternal Anvil (Backend)
 * The backend server for the Eternal Anvil.
 * OpenAPI spec version: v0.0.1
 */

export type RealmManagerAccountsRemoveUser403ErrorsItemAttr = typeof RealmManagerAccountsRemoveUser403ErrorsItemAttr[keyof typeof RealmManagerAccountsRemoveUser403ErrorsItemAttr];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const RealmManagerAccountsRemoveUser403ErrorsItemAttr = {
  user: 'user',
} as const;
