/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Eternal Anvil (Backend)
 * The backend server for the Eternal Anvil.
 * OpenAPI spec version: v0.0.1
 */

/**
 * * `invalid_choice` - invalid_choice
* `null` - null
* `required` - required
 */
export type RealmManagerAccountsCreateRaceErrorComponentCode = typeof RealmManagerAccountsCreateRaceErrorComponentCode[keyof typeof RealmManagerAccountsCreateRaceErrorComponentCode];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const RealmManagerAccountsCreateRaceErrorComponentCode = {
  invalid_choice: 'invalid_choice',
  null: 'null',
  required: 'required',
} as const;
