/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Eternal Anvil (Backend)
 * The backend server for the Eternal Anvil.
 * OpenAPI spec version: v0.0.1
 */

export type RealmManagerAccountsRemoveUser403Type = typeof RealmManagerAccountsRemoveUser403Type[keyof typeof RealmManagerAccountsRemoveUser403Type];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const RealmManagerAccountsRemoveUser403Type = {
  client_error: 'client_error',
} as const;
