/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Eternal Anvil (Backend)
 * The backend server for the Eternal Anvil.
 * OpenAPI spec version: v0.0.1
 */
import type { RealmManagerAccountsDestroy403ErrorsItem } from './realmManagerAccountsDestroy403ErrorsItem';
import type { RealmManagerAccountsDestroy403Type } from './realmManagerAccountsDestroy403Type';

export type RealmManagerAccountsDestroy403 = {
  errors: RealmManagerAccountsDestroy403ErrorsItem[];
  type: RealmManagerAccountsDestroy403Type;
};
