/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Eternal Anvil (Backend)
 * The backend server for the Eternal Anvil.
 * OpenAPI spec version: v0.0.1
 */
import type { ParseErrorResponse } from './parseErrorResponse';
import type { RealmManagerAccountsJoinValidationError } from './realmManagerAccountsJoinValidationError';

export type RealmManagerAccountsJoinErrorResponse400 = RealmManagerAccountsJoinValidationError | ParseErrorResponse;
