/**
 * Generated by orval v7.0.1 🍺
 * Do not edit manually.
 * Eternal Anvil (Backend)
 * The backend server for the Eternal Anvil.
 * OpenAPI spec version: v0.0.1
 */

/**
 * * `not_a_list` - not_a_list
* `null` - null
 */
export type RealmManagerAccountsSchedulePartialUpdateSaturdayErrorComponentCode = typeof RealmManagerAccountsSchedulePartialUpdateSaturdayErrorComponentCode[keyof typeof RealmManagerAccountsSchedulePartialUpdateSaturdayErrorComponentCode];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const RealmManagerAccountsSchedulePartialUpdateSaturdayErrorComponentCode = {
  not_a_list: 'not_a_list',
  null: 'null',
} as const;
