/**
 * Generated by orval v7.0.1 🍺
 * Do not edit manually.
 * Eternal Anvil (Backend)
 * The backend server for the Eternal Anvil.
 * OpenAPI spec version: v0.0.1
 */
import type { RealmManagerAccountsScheduleUpdateNonFieldErrorsErrorComponentAttr } from './realmManagerAccountsScheduleUpdateNonFieldErrorsErrorComponentAttr';
import type { RealmManagerAccountsScheduleUpdateNonFieldErrorsErrorComponentCode } from './realmManagerAccountsScheduleUpdateNonFieldErrorsErrorComponentCode';

export interface RealmManagerAccountsScheduleUpdateNonFieldErrorsErrorComponent {
  attr: RealmManagerAccountsScheduleUpdateNonFieldErrorsErrorComponentAttr;
  /** * `invalid` - invalid
* `null` - null */
  code: RealmManagerAccountsScheduleUpdateNonFieldErrorsErrorComponentCode;
  detail: string;
}
