/**
 * Generated by orval v7.0.1 🍺
 * Do not edit manually.
 * Eternal Anvil (Backend)
 * The backend server for the Eternal Anvil.
 * OpenAPI spec version: v0.0.1
 */

export type RealmManagerAccountsSchedulePartialUpdateMondayINDEXErrorComponentAttr = typeof RealmManagerAccountsSchedulePartialUpdateMondayINDEXErrorComponentAttr[keyof typeof RealmManagerAccountsSchedulePartialUpdateMondayINDEXErrorComponentAttr];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const RealmManagerAccountsSchedulePartialUpdateMondayINDEXErrorComponentAttr = {
  mondayINDEX: 'monday.INDEX',
} as const;
