/**
 * Generated by orval v7.0.1 🍺
 * Do not edit manually.
 * Eternal Anvil (Backend)
 * The backend server for the Eternal Anvil.
 * OpenAPI spec version: v0.0.1
 */
import type { RealmManagerAccountsSchedulePartialUpdateSaturdayErrorComponentAttr } from './realmManagerAccountsSchedulePartialUpdateSaturdayErrorComponentAttr';
import type { RealmManagerAccountsSchedulePartialUpdateSaturdayErrorComponentCode } from './realmManagerAccountsSchedulePartialUpdateSaturdayErrorComponentCode';

export interface RealmManagerAccountsSchedulePartialUpdateSaturdayErrorComponent {
  attr: RealmManagerAccountsSchedulePartialUpdateSaturdayErrorComponentAttr;
  /** * `not_a_list` - not_a_list
* `null` - null */
  code: RealmManagerAccountsSchedulePartialUpdateSaturdayErrorComponentCode;
  detail: string;
}
