/**
 * Generated by orval v7.0.1 🍺
 * Do not edit manually.
 * Eternal Anvil (Backend)
 * The backend server for the Eternal Anvil.
 * OpenAPI spec version: v0.0.1
 */

export type RealmManagerAccountsScheduleUpdateTuesdayErrorComponentAttr = typeof RealmManagerAccountsScheduleUpdateTuesdayErrorComponentAttr[keyof typeof RealmManagerAccountsScheduleUpdateTuesdayErrorComponentAttr];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const RealmManagerAccountsScheduleUpdateTuesdayErrorComponentAttr = {
  tuesday: 'tuesday',
} as const;
