/**
 * Generated by orval v7.0.1 🍺
 * Do not edit manually.
 * Eternal Anvil (Backend)
 * The backend server for the Eternal Anvil.
 * OpenAPI spec version: v0.0.1
 */
import type { RealmManagerAccountsScheduleUpdateTuesdayErrorComponentAttr } from './realmManagerAccountsScheduleUpdateTuesdayErrorComponentAttr';
import type { RealmManagerAccountsScheduleUpdateTuesdayErrorComponentCode } from './realmManagerAccountsScheduleUpdateTuesdayErrorComponentCode';

export interface RealmManagerAccountsScheduleUpdateTuesdayErrorComponent {
  attr: RealmManagerAccountsScheduleUpdateTuesdayErrorComponentAttr;
  /** * `not_a_list` - not_a_list
* `null` - null */
  code: RealmManagerAccountsScheduleUpdateTuesdayErrorComponentCode;
  detail: string;
}
