/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Eternal Anvil (Backend)
 * The backend server for the Eternal Anvil.
 * OpenAPI spec version: v0.0.1
 */

export type RealmManagerAccountsCreateRaceErrorComponentAttr = typeof RealmManagerAccountsCreateRaceErrorComponentAttr[keyof typeof RealmManagerAccountsCreateRaceErrorComponentAttr];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const RealmManagerAccountsCreateRaceErrorComponentAttr = {
  race: 'race',
} as const;
