/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Eternal Anvil (Backend)
 * The backend server for the Eternal Anvil.
 * OpenAPI spec version: v0.0.1
 */
import type { RealmManagerAccountsJoinCreate403ErrorsItemAttr } from './realmManagerAccountsJoinCreate403ErrorsItemAttr';
import type { RealmManagerAccountsJoinCreate403ErrorsItemCode } from './realmManagerAccountsJoinCreate403ErrorsItemCode';
import type { RealmManagerAccountsJoinCreate403ErrorsItemDetail } from './realmManagerAccountsJoinCreate403ErrorsItemDetail';

export type RealmManagerAccountsJoinCreate403ErrorsItem = {
  attr: RealmManagerAccountsJoinCreate403ErrorsItemAttr;
  code: RealmManagerAccountsJoinCreate403ErrorsItemCode;
  detail: RealmManagerAccountsJoinCreate403ErrorsItemDetail;
};
