/**
 * Generated by orval v7.0.1 🍺
 * Do not edit manually.
 * Eternal Anvil (Backend)
 * The backend server for the Eternal Anvil.
 * OpenAPI spec version: v0.0.1
 */
import type { RealmManagerAccountsSchedulePartialUpdateFridayINDEXErrorComponentAttr } from './realmManagerAccountsSchedulePartialUpdateFridayINDEXErrorComponentAttr';
import type { RealmManagerAccountsSchedulePartialUpdateFridayINDEXErrorComponentCode } from './realmManagerAccountsSchedulePartialUpdateFridayINDEXErrorComponentCode';

export interface RealmManagerAccountsSchedulePartialUpdateFridayINDEXErrorComponent {
  attr: RealmManagerAccountsSchedulePartialUpdateFridayINDEXErrorComponentAttr;
  /** * `invalid` - invalid
* `max_string_length` - max_string_length
* `max_value` - max_value
* `min_value` - min_value
* `null` - null
* `required` - required */
  code: RealmManagerAccountsSchedulePartialUpdateFridayINDEXErrorComponentCode;
  detail: string;
}
