/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Eternal Anvil (Backend)
 * The backend server for the Eternal Anvil.
 * OpenAPI spec version: v0.0.1
 */
import type { RealmManagerAccountsJoinCreateNonFieldErrorsErrorComponentAttr } from './realmManagerAccountsJoinCreateNonFieldErrorsErrorComponentAttr';
import type { RealmManagerAccountsJoinCreateNonFieldErrorsErrorComponentCode } from './realmManagerAccountsJoinCreateNonFieldErrorsErrorComponentCode';

export interface RealmManagerAccountsJoinCreateNonFieldErrorsErrorComponent {
  attr: RealmManagerAccountsJoinCreateNonFieldErrorsErrorComponentAttr;
  /** * `invalid` - invalid
* `null` - null */
  code: RealmManagerAccountsJoinCreateNonFieldErrorsErrorComponentCode;
  detail: string;
}
