/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Eternal Anvil (Backend)
 * The backend server for the Eternal Anvil.
 * OpenAPI spec version: v0.0.1
 */

export type RealmManagerAccountsDestroy403ErrorsItemCode = typeof RealmManagerAccountsDestroy403ErrorsItemCode[keyof typeof RealmManagerAccountsDestroy403ErrorsItemCode];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const RealmManagerAccountsDestroy403ErrorsItemCode = {
  permission_denied: 'permission_denied',
} as const;
