/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Eternal Anvil (Backend)
 * The backend server for the Eternal Anvil.
 * OpenAPI spec version: v0.0.1
 */
import type { RealmManagerAccountsRemoveUser403ErrorsItem } from './realmManagerAccountsRemoveUser403ErrorsItem';
import type { RealmManagerAccountsRemoveUser403Type } from './realmManagerAccountsRemoveUser403Type';

export type RealmManagerAccountsRemoveUser403 = {
  errors: RealmManagerAccountsRemoveUser403ErrorsItem[];
  type: RealmManagerAccountsRemoveUser403Type;
};
