/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Eternal Anvil (Backend)
 * The backend server for the Eternal Anvil.
 * OpenAPI spec version: v0.0.1
 */
import type { RealmManagerAccountsJoinCreateIdErrorComponent } from './realmManagerAccountsJoinCreateIdErrorComponent';
import type { RealmManagerAccountsJoinCreateNonFieldErrorsErrorComponent } from './realmManagerAccountsJoinCreateNonFieldErrorsErrorComponent';

export type RealmManagerAccountsJoinCreateError = RealmManagerAccountsJoinCreateNonFieldErrorsErrorComponent | RealmManagerAccountsJoinCreateIdErrorComponent;
