/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Eternal Anvil (Backend)
 * The backend server for the Eternal Anvil.
 * OpenAPI spec version: v0.0.1
 */
import type { RealmManagerAccountsUpdate403ErrorsItemAttr } from './realmManagerAccountsUpdate403ErrorsItemAttr';
import type { RealmManagerAccountsUpdate403ErrorsItemCode } from './realmManagerAccountsUpdate403ErrorsItemCode';
import type { RealmManagerAccountsUpdate403ErrorsItemDetail } from './realmManagerAccountsUpdate403ErrorsItemDetail';

export type RealmManagerAccountsUpdate403ErrorsItem = {
  attr: RealmManagerAccountsUpdate403ErrorsItemAttr;
  code: RealmManagerAccountsUpdate403ErrorsItemCode;
  detail: RealmManagerAccountsUpdate403ErrorsItemDetail;
};
