/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Eternal Anvil (Backend)
 * The backend server for the Eternal Anvil.
 * OpenAPI spec version: v0.0.1
 */

/**
 * * `invalid` - invalid
* `null` - null
* `required` - required
 */
export type RealmManagerAccountsJoinIdErrorComponentCode = typeof RealmManagerAccountsJoinIdErrorComponentCode[keyof typeof RealmManagerAccountsJoinIdErrorComponentCode];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const RealmManagerAccountsJoinIdErrorComponentCode = {
  invalid: 'invalid',
  null: 'null',
  required: 'required',
} as const;
