/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Eternal Anvil (Backend)
 * The backend server for the Eternal Anvil.
 * OpenAPI spec version: v0.0.1
 */
import type { RealmManagerAccountsJoin403ErrorsItem } from './realmManagerAccountsJoin403ErrorsItem';
import type { RealmManagerAccountsJoin403Type } from './realmManagerAccountsJoin403Type';

export type RealmManagerAccountsJoin403 = {
  errors: RealmManagerAccountsJoin403ErrorsItem[];
  type: RealmManagerAccountsJoin403Type;
};
