/**
 * Generated by orval v7.0.1 🍺
 * Do not edit manually.
 * Eternal Anvil (Backend)
 * The backend server for the Eternal Anvil.
 * OpenAPI spec version: v0.0.1
 */
import type { RealmManagerAccountsJoinNonFieldErrorsErrorComponentAttr } from './realmManagerAccountsJoinNonFieldErrorsErrorComponentAttr';
import type { RealmManagerAccountsJoinNonFieldErrorsErrorComponentCode } from './realmManagerAccountsJoinNonFieldErrorsErrorComponentCode';

export interface RealmManagerAccountsJoinNonFieldErrorsErrorComponent {
  attr: RealmManagerAccountsJoinNonFieldErrorsErrorComponentAttr;
  /** * `invalid` - invalid
* `null` - null */
  code: RealmManagerAccountsJoinNonFieldErrorsErrorComponentCode;
  detail: string;
}
