/**
 * Generated by orval v7.0.1 🍺
 * Do not edit manually.
 * Eternal Anvil (Backend)
 * The backend server for the Eternal Anvil.
 * OpenAPI spec version: v0.0.1
 */
import type { RealmManagerAccountsSchedulePartialUpdateTuesdayErrorComponentAttr } from './realmManagerAccountsSchedulePartialUpdateTuesdayErrorComponentAttr';
import type { RealmManagerAccountsSchedulePartialUpdateTuesdayErrorComponentCode } from './realmManagerAccountsSchedulePartialUpdateTuesdayErrorComponentCode';

export interface RealmManagerAccountsSchedulePartialUpdateTuesdayErrorComponent {
  attr: RealmManagerAccountsSchedulePartialUpdateTuesdayErrorComponentAttr;
  /** * `not_a_list` - not_a_list
* `null` - null */
  code: RealmManagerAccountsSchedulePartialUpdateTuesdayErrorComponentCode;
  detail: string;
}
