/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Eternal Anvil (Backend)
 * The backend server for the Eternal Anvil.
 * OpenAPI spec version: v0.0.1
 */
import type { RealmManagerAccountsJoinCreateError } from './realmManagerAccountsJoinCreateError';
import type { RealmManagerAccountsJoinCreateValidationErrorType } from './realmManagerAccountsJoinCreateValidationErrorType';

export interface RealmManagerAccountsJoinCreateValidationError {
  errors: RealmManagerAccountsJoinCreateError[];
  type: RealmManagerAccountsJoinCreateValidationErrorType;
}
