/**
 * Generated by orval v7.0.1 🍺
 * Do not edit manually.
 * Eternal Anvil (Backend)
 * The backend server for the Eternal Anvil.
 * OpenAPI spec version: v0.0.1
 */
import type { RealmManagerAccountsSchedulePartialUpdateSundayErrorComponentAttr } from './realmManagerAccountsSchedulePartialUpdateSundayErrorComponentAttr';
import type { RealmManagerAccountsSchedulePartialUpdateSundayErrorComponentCode } from './realmManagerAccountsSchedulePartialUpdateSundayErrorComponentCode';

export interface RealmManagerAccountsSchedulePartialUpdateSundayErrorComponent {
  attr: RealmManagerAccountsSchedulePartialUpdateSundayErrorComponentAttr;
  /** * `not_a_list` - not_a_list
* `null` - null */
  code: RealmManagerAccountsSchedulePartialUpdateSundayErrorComponentCode;
  detail: string;
}
