/**
 * Generated by orval v7.0.1 🍺
 * Do not edit manually.
 * Eternal Anvil (Backend)
 * The backend server for the Eternal Anvil.
 * OpenAPI spec version: v0.0.1
 */
import type { RealmManagerAccountsUpdateNonFieldErrorsErrorComponentAttr } from './realmManagerAccountsUpdateNonFieldErrorsErrorComponentAttr';
import type { RealmManagerAccountsUpdateNonFieldErrorsErrorComponentCode } from './realmManagerAccountsUpdateNonFieldErrorsErrorComponentCode';

export interface RealmManagerAccountsUpdateNonFieldErrorsErrorComponent {
  attr: RealmManagerAccountsUpdateNonFieldErrorsErrorComponentAttr;
  /** * `invalid` - invalid
* `null` - null */
  code: RealmManagerAccountsUpdateNonFieldErrorsErrorComponentCode;
  detail: string;
}
