/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Eternal Anvil (Backend)
 * The backend server for the Eternal Anvil.
 * OpenAPI spec version: v0.0.1
 */

export type RealmManagerAccountsJoin403ErrorsItemAttr = typeof RealmManagerAccountsJoin403ErrorsItemAttr[keyof typeof RealmManagerAccountsJoin403ErrorsItemAttr];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const RealmManagerAccountsJoin403ErrorsItemAttr = {
  user: 'user',
} as const;
