/**
 * Generated by orval v7.0.1 🍺
 * Do not edit manually.
 * Eternal Anvil (Backend)
 * The backend server for the Eternal Anvil.
 * OpenAPI spec version: v0.0.1
 */
import type { RealmManagerAccountsSchedulePartialUpdateFridayErrorComponentAttr } from './realmManagerAccountsSchedulePartialUpdateFridayErrorComponentAttr';
import type { RealmManagerAccountsSchedulePartialUpdateFridayErrorComponentCode } from './realmManagerAccountsSchedulePartialUpdateFridayErrorComponentCode';

export interface RealmManagerAccountsSchedulePartialUpdateFridayErrorComponent {
  attr: RealmManagerAccountsSchedulePartialUpdateFridayErrorComponentAttr;
  /** * `not_a_list` - not_a_list
* `null` - null */
  code: RealmManagerAccountsSchedulePartialUpdateFridayErrorComponentCode;
  detail: string;
}
