/**
 * Generated by orval v7.0.1 🍺
 * Do not edit manually.
 * Eternal Anvil (Backend)
 * The backend server for the Eternal Anvil.
 * OpenAPI spec version: v0.0.1
 */

export type RealmManagerAccountsLeave403ErrorsItemAttr = typeof RealmManagerAccountsLeave403ErrorsItemAttr[keyof typeof RealmManagerAccountsLeave403ErrorsItemAttr];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const RealmManagerAccountsLeave403ErrorsItemAttr = {
  owner: 'owner',
} as const;
