/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Eternal Anvil (Backend)
 * The backend server for the Eternal Anvil.
 * OpenAPI spec version: v0.0.1
 */

export type RealmManagerAccountsCreateGameWorldErrorComponentAttr = typeof RealmManagerAccountsCreateGameWorldErrorComponentAttr[keyof typeof RealmManagerAccountsCreateGameWorldErrorComponentAttr];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const RealmManagerAccountsCreateGameWorldErrorComponentAttr = {
  game_world: 'game_world',
} as const;
