/**
 * Generated by orval v7.0.1 🍺
 * Do not edit manually.
 * Eternal Anvil (Backend)
 * The backend server for the Eternal Anvil.
 * OpenAPI spec version: v0.0.1
 */
import type { RealmManagerAccountsJoinIdErrorComponentAttr } from './realmManagerAccountsJoinIdErrorComponentAttr';
import type { RealmManagerAccountsJoinIdErrorComponentCode } from './realmManagerAccountsJoinIdErrorComponentCode';

export interface RealmManagerAccountsJoinIdErrorComponent {
  attr: RealmManagerAccountsJoinIdErrorComponentAttr;
  /** * `invalid` - invalid
* `null` - null
* `required` - required */
  code: RealmManagerAccountsJoinIdErrorComponentCode;
  detail: string;
}
