/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Eternal Anvil (Backend)
 * The backend server for the Eternal Anvil.
 * OpenAPI spec version: v0.0.1
 */

export type RealmManagerAccountsUpdate403ErrorsItemCode = typeof RealmManagerAccountsUpdate403ErrorsItemCode[keyof typeof RealmManagerAccountsUpdate403ErrorsItemCode];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const RealmManagerAccountsUpdate403ErrorsItemCode = {
  permission_denied: 'permission_denied',
} as const;
