/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Eternal Anvil (Backend)
 * The backend server for the Eternal Anvil.
 * OpenAPI spec version: v0.0.1
 */

export type RealmManagerAccountsUpdate403ErrorsItemDetail = typeof RealmManagerAccountsUpdate403ErrorsItemDetail[keyof typeof RealmManagerAccountsUpdate403ErrorsItemDetail];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const RealmManagerAccountsUpdate403ErrorsItemDetail = {
  You_must_be_the_account_owner_to_perform_this_operation: 'You must be the account owner to perform this operation.',
} as const;
