/**
 * Generated by orval v7.0.1 🍺
 * Do not edit manually.
 * Eternal Anvil (Backend)
 * The backend server for the Eternal Anvil.
 * OpenAPI spec version: v0.0.1
 */
import type { RealmManagerAccountsSchedulePartialUpdateTuesdayINDEXErrorComponentAttr } from './realmManagerAccountsSchedulePartialUpdateTuesdayINDEXErrorComponentAttr';
import type { RealmManagerAccountsSchedulePartialUpdateTuesdayINDEXErrorComponentCode } from './realmManagerAccountsSchedulePartialUpdateTuesdayINDEXErrorComponentCode';

export interface RealmManagerAccountsSchedulePartialUpdateTuesdayINDEXErrorComponent {
  attr: RealmManagerAccountsSchedulePartialUpdateTuesdayINDEXErrorComponentAttr;
  /** * `invalid` - invalid
* `max_string_length` - max_string_length
* `max_value` - max_value
* `min_value` - min_value
* `null` - null
* `required` - required */
  code: RealmManagerAccountsSchedulePartialUpdateTuesdayINDEXErrorComponentCode;
  detail: string;
}
