/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Eternal Anvil (Backend)
 * The backend server for the Eternal Anvil.
 * OpenAPI spec version: v0.0.1
 */
import type { RealmManagerAccountsRemoveUser403ErrorsItemAttr } from './realmManagerAccountsRemoveUser403ErrorsItemAttr';
import type { RealmManagerAccountsRemoveUser403ErrorsItemCode } from './realmManagerAccountsRemoveUser403ErrorsItemCode';
import type { RealmManagerAccountsRemoveUser403ErrorsItemDetail } from './realmManagerAccountsRemoveUser403ErrorsItemDetail';

export type RealmManagerAccountsRemoveUser403ErrorsItem = {
  attr: RealmManagerAccountsRemoveUser403ErrorsItemAttr;
  code: RealmManagerAccountsRemoveUser403ErrorsItemCode;
  detail: RealmManagerAccountsRemoveUser403ErrorsItemDetail;
};
