/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Eternal Anvil (Backend)
 * The backend server for the Eternal Anvil.
 * OpenAPI spec version: v0.0.1
 */

export type RealmManagerAccountsLeave403Type = typeof RealmManagerAccountsLeave403Type[keyof typeof RealmManagerAccountsLeave403Type];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const RealmManagerAccountsLeave403Type = {
  validation_error: 'validation_error',
} as const;
