/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Eternal Anvil (Backend)
 * The backend server for the Eternal Anvil.
 * OpenAPI spec version: v0.0.1
 */
import type { RealmManagerAccountsUpdateOwnerErrorComponentAttr } from './realmManagerAccountsUpdateOwnerErrorComponentAttr';
import type { RealmManagerAccountsUpdateOwnerErrorComponentCode } from './realmManagerAccountsUpdateOwnerErrorComponentCode';

export interface RealmManagerAccountsUpdateOwnerErrorComponent {
  attr: RealmManagerAccountsUpdateOwnerErrorComponentAttr;
  /** * `does_not_exist` - does_not_exist
* `incorrect_type` - incorrect_type
* `null` - null
* `required` - required */
  code: RealmManagerAccountsUpdateOwnerErrorComponentCode;
  detail: string;
}
