/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Eternal Anvil (Backend)
 * The backend server for the Eternal Anvil.
 * OpenAPI spec version: v0.0.1
 */

export type RealmManagerAccountsDestroy403ErrorsItemAttr = typeof RealmManagerAccountsDestroy403ErrorsItemAttr[keyof typeof RealmManagerAccountsDestroy403ErrorsItemAttr];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const RealmManagerAccountsDestroy403ErrorsItemAttr = {
  user: 'user',
} as const;
