/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Eternal Anvil (Backend)
 * The backend server for the Eternal Anvil.
 * OpenAPI spec version: v0.0.1
 */

export type RealmManagerAccountsDestroy403ErrorsItemDetail = typeof RealmManagerAccountsDestroy403ErrorsItemDetail[keyof typeof RealmManagerAccountsDestroy403ErrorsItemDetail];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const RealmManagerAccountsDestroy403ErrorsItemDetail = {
  You_must_be_the_account_owner_to_perform_this_operation: 'You must be the account owner to perform this operation.',
} as const;
