/**
 * Generated by orval v7.0.1 🍺
 * Do not edit manually.
 * Eternal Anvil (Backend)
 * The backend server for the Eternal Anvil.
 * OpenAPI spec version: v0.0.1
 */

export type RealmManagerAccountsUpdateValidationErrorType = typeof RealmManagerAccountsUpdateValidationErrorType[keyof typeof RealmManagerAccountsUpdateValidationErrorType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const RealmManagerAccountsUpdateValidationErrorType = {
  validation_error: 'validation_error',
} as const;
