/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Eternal Anvil (Backend)
 * The backend server for the Eternal Anvil.
 * OpenAPI spec version: v0.0.1
 */

export interface TokenObtainPairRequest {
  /** @minLength 1 */
  password: string;
  /** @minLength 1 */
  username: string;
}
