/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Eternal Anvil (Backend)
 * The backend server for the Eternal Anvil.
 * OpenAPI spec version: v0.0.1
 */
import type { UsersLogoutCreateNonFieldErrorsErrorComponent } from './usersLogoutCreateNonFieldErrorsErrorComponent';
import type { UsersLogoutCreateRefreshErrorComponent } from './usersLogoutCreateRefreshErrorComponent';

export type UsersLogoutCreateError = UsersLogoutCreateNonFieldErrorsErrorComponent | UsersLogoutCreateRefreshErrorComponent;
