/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Eternal Anvil (Backend)
 * The backend server for the Eternal Anvil.
 * OpenAPI spec version: v0.0.1
 */

export type UsersChangePasswordCreate401ErrorsItemCode = typeof UsersChangePasswordCreate401ErrorsItemCode[keyof typeof UsersChangePasswordCreate401ErrorsItemCode];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const UsersChangePasswordCreate401ErrorsItemCode = {
  authentication_failed: 'authentication_failed',
} as const;
