/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Eternal Anvil (Backend)
 * The backend server for the Eternal Anvil.
 * OpenAPI spec version: v0.0.1
 */

export type UsersChangePasswordCreate401ErrorsItemDetail = typeof UsersChangePasswordCreate401ErrorsItemDetail[keyof typeof UsersChangePasswordCreate401ErrorsItemDetail];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const UsersChangePasswordCreate401ErrorsItemDetail = {
  Wrong_password: 'Wrong password.',
} as const;
