/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Eternal Anvil (Backend)
 * The backend server for the Eternal Anvil.
 * OpenAPI spec version: v0.0.1
 */

export type UsersRegister403Type = typeof UsersRegister403Type[keyof typeof UsersRegister403Type];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const UsersRegister403Type = {
  client_error: 'client_error',
} as const;
