/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Eternal Anvil (Backend)
 * The backend server for the Eternal Anvil.
 * OpenAPI spec version: v0.0.1
 */
import type { UsersRegisterNonFieldErrorsErrorComponent } from './usersRegisterNonFieldErrorsErrorComponent';
import type { UsersRegisterPasswordErrorComponent } from './usersRegisterPasswordErrorComponent';
import type { UsersRegisterUsernameErrorComponent } from './usersRegisterUsernameErrorComponent';

export type UsersRegisterError = UsersRegisterNonFieldErrorsErrorComponent | UsersRegisterUsernameErrorComponent | UsersRegisterPasswordErrorComponent;
