/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Eternal Anvil (Backend)
 * The backend server for the Eternal Anvil.
 * OpenAPI spec version: v0.0.1
 */

export type UsersRegisterNonFieldErrorsErrorComponentAttr = typeof UsersRegisterNonFieldErrorsErrorComponentAttr[keyof typeof UsersRegisterNonFieldErrorsErrorComponentAttr];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const UsersRegisterNonFieldErrorsErrorComponentAttr = {
  non_field_errors: 'non_field_errors',
} as const;
