/**
 * Generated by orval v7.0.1 🍺
 * Do not edit manually.
 * Eternal Anvil (Backend)
 * The backend server for the Eternal Anvil.
 * OpenAPI spec version: v0.0.1
 */

/**
 * Serializer for creating users.
 */
export interface UserRegisterRequest {
  /**
   * @minLength 1
   * @maxLength 128
   */
  password: string;
  /**
   * @minLength 1
   * @maxLength 255
   */
  username: string;
}
