/**
 * Generated by orval v7.0.1 🍺
 * Do not edit manually.
 * Eternal Anvil (Backend)
 * The backend server for the Eternal Anvil.
 * OpenAPI spec version: v0.0.1
 */

export type UsersDiscordLoginCodeErrorComponentAttr = typeof UsersDiscordLoginCodeErrorComponentAttr[keyof typeof UsersDiscordLoginCodeErrorComponentAttr];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const UsersDiscordLoginCodeErrorComponentAttr = {
  code: 'code',
} as const;
