/**
 * Generated by orval v7.0.1 🍺
 * Do not edit manually.
 * Eternal Anvil (Backend)
 * The backend server for the Eternal Anvil.
 * OpenAPI spec version: v0.0.1
 */

export type UsersLoginRefreshValidationErrorType = typeof UsersLoginRefreshValidationErrorType[keyof typeof UsersLoginRefreshValidationErrorType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const UsersLoginRefreshValidationErrorType = {
  validation_error: 'validation_error',
} as const;
