/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Eternal Anvil (Backend)
 * The backend server for the Eternal Anvil.
 * OpenAPI spec version: v0.0.1
 */

export type UsersChangePassword401Type = typeof UsersChangePassword401Type[keyof typeof UsersChangePassword401Type];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const UsersChangePassword401Type = {
  client_error: 'client_error',
} as const;
