/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Eternal Anvil (Backend)
 * The backend server for the Eternal Anvil.
 * OpenAPI spec version: v0.0.1
 */

/**
 * * `invalid` - invalid
* `null` - null
 */
export type UsersRegisterNonFieldErrorsErrorComponentCode = typeof UsersRegisterNonFieldErrorsErrorComponentCode[keyof typeof UsersRegisterNonFieldErrorsErrorComponentCode];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const UsersRegisterNonFieldErrorsErrorComponentCode = {
  invalid: 'invalid',
  null: 'null',
} as const;
