/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Eternal Anvil (Backend)
 * The backend server for the Eternal Anvil.
 * OpenAPI spec version: v0.0.1
 */
import type { UsersLoginError } from './usersLoginError';
import type { UsersLoginValidationErrorType } from './usersLoginValidationErrorType';

export interface UsersLoginValidationError {
  errors: UsersLoginError[];
  type: UsersLoginValidationErrorType;
}
