/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Eternal Anvil (Backend)
 * The backend server for the Eternal Anvil.
 * OpenAPI spec version: v0.0.1
 */
import type { UsersRegisterCreate403ErrorsItemAttr } from './usersRegisterCreate403ErrorsItemAttr';
import type { UsersRegisterCreate403ErrorsItemCode } from './usersRegisterCreate403ErrorsItemCode';
import type { UsersRegisterCreate403ErrorsItemDetail } from './usersRegisterCreate403ErrorsItemDetail';

export type UsersRegisterCreate403ErrorsItem = {
  attr: UsersRegisterCreate403ErrorsItemAttr;
  code: UsersRegisterCreate403ErrorsItemCode;
  detail: UsersRegisterCreate403ErrorsItemDetail;
};
