/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Eternal Anvil (Backend)
 * The backend server for the Eternal Anvil.
 * OpenAPI spec version: v0.0.1
 */
import type { UsersLoginCreateNonFieldErrorsErrorComponent } from './usersLoginCreateNonFieldErrorsErrorComponent';
import type { UsersLoginCreatePasswordErrorComponent } from './usersLoginCreatePasswordErrorComponent';
import type { UsersLoginCreateUsernameErrorComponent } from './usersLoginCreateUsernameErrorComponent';

export type UsersLoginCreateError = UsersLoginCreateNonFieldErrorsErrorComponent | UsersLoginCreateUsernameErrorComponent | UsersLoginCreatePasswordErrorComponent;
