/**
 * Generated by orval v7.0.1 🍺
 * Do not edit manually.
 * Eternal Anvil (Backend)
 * The backend server for the Eternal Anvil.
 * OpenAPI spec version: v0.0.1
 */

export type UsersChangePassword401ErrorsItemDetail = typeof UsersChangePassword401ErrorsItemDetail[keyof typeof UsersChangePassword401ErrorsItemDetail];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const UsersChangePassword401ErrorsItemDetail = {
  Wrong_password: 'Wrong password.',
} as const;
