/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Eternal Anvil (Backend)
 * The backend server for the Eternal Anvil.
 * OpenAPI spec version: v0.0.1
 */
import type { UsersChangePassword401ErrorsItemAttr } from './usersChangePassword401ErrorsItemAttr';
import type { UsersChangePassword401ErrorsItemCode } from './usersChangePassword401ErrorsItemCode';
import type { UsersChangePassword401ErrorsItemDetail } from './usersChangePassword401ErrorsItemDetail';

export type UsersChangePassword401ErrorsItem = {
  attr: UsersChangePassword401ErrorsItemAttr;
  code: UsersChangePassword401ErrorsItemCode;
  detail: UsersChangePassword401ErrorsItemDetail;
};
