/**
 * Generated by orval v7.0.1 🍺
 * Do not edit manually.
 * Eternal Anvil (Backend)
 * The backend server for the Eternal Anvil.
 * OpenAPI spec version: v0.0.1
 */

export type UsersProfileUpdateUsernameErrorComponentAttr = typeof UsersProfileUpdateUsernameErrorComponentAttr[keyof typeof UsersProfileUpdateUsernameErrorComponentAttr];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const UsersProfileUpdateUsernameErrorComponentAttr = {
  username: 'username',
} as const;
