/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Eternal Anvil (Backend)
 * The backend server for the Eternal Anvil.
 * OpenAPI spec version: v0.0.1
 */

/**
 * Serializer for creating users.
 */
export interface UserRegister {
  readonly id: string;
  /** @maxLength 128 */
  password: string;
  /** @maxLength 255 */
  username: string;
}
