/**
 * Generated by orval v7.0.1 🍺
 * Do not edit manually.
 * Eternal Anvil (Backend)
 * The backend server for the Eternal Anvil.
 * OpenAPI spec version: v0.0.1
 */
import type { UsersProfileUpdateNonFieldErrorsErrorComponentAttr } from './usersProfileUpdateNonFieldErrorsErrorComponentAttr';
import type { UsersProfileUpdateNonFieldErrorsErrorComponentCode } from './usersProfileUpdateNonFieldErrorsErrorComponentCode';

export interface UsersProfileUpdateNonFieldErrorsErrorComponent {
  attr: UsersProfileUpdateNonFieldErrorsErrorComponentAttr;
  /** * `invalid` - invalid
* `null` - null */
  code: UsersProfileUpdateNonFieldErrorsErrorComponentCode;
  detail: string;
}
