/**
 * Generated by orval v7.0.1 🍺
 * Do not edit manually.
 * Eternal Anvil (Backend)
 * The backend server for the Eternal Anvil.
 * OpenAPI spec version: v0.0.1
 */

export type UsersLogoutRefreshErrorComponentAttr = typeof UsersLogoutRefreshErrorComponentAttr[keyof typeof UsersLogoutRefreshErrorComponentAttr];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const UsersLogoutRefreshErrorComponentAttr = {
  refresh: 'refresh',
} as const;
