/**
 * Generated by orval v7.0.1 🍺
 * Do not edit manually.
 * Eternal Anvil (Backend)
 * The backend server for the Eternal Anvil.
 * OpenAPI spec version: v0.0.1
 */
import type { UsersDiscordLoginNonFieldErrorsErrorComponentAttr } from './usersDiscordLoginNonFieldErrorsErrorComponentAttr';
import type { UsersDiscordLoginNonFieldErrorsErrorComponentCode } from './usersDiscordLoginNonFieldErrorsErrorComponentCode';

export interface UsersDiscordLoginNonFieldErrorsErrorComponent {
  attr: UsersDiscordLoginNonFieldErrorsErrorComponentAttr;
  /** * `invalid` - invalid
* `null` - null */
  code: UsersDiscordLoginNonFieldErrorsErrorComponentCode;
  detail: string;
}
