/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Eternal Anvil (Backend)
 * The backend server for the Eternal Anvil.
 * OpenAPI spec version: v0.0.1
 */
import type { UsersChangePasswordNewPasswordErrorComponent } from './usersChangePasswordNewPasswordErrorComponent';
import type { UsersChangePasswordNonFieldErrorsErrorComponent } from './usersChangePasswordNonFieldErrorsErrorComponent';
import type { UsersChangePasswordPasswordErrorComponent } from './usersChangePasswordPasswordErrorComponent';

export type UsersChangePasswordError = UsersChangePasswordNonFieldErrorsErrorComponent | UsersChangePasswordPasswordErrorComponent | UsersChangePasswordNewPasswordErrorComponent;
