/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Eternal Anvil (Backend)
 * The backend server for the Eternal Anvil.
 * OpenAPI spec version: v0.0.1
 */
import type { UsersProfileUpdateError } from './usersProfileUpdateError';
import type { UsersProfileUpdateValidationErrorType } from './usersProfileUpdateValidationErrorType';

export interface UsersProfileUpdateValidationError {
  errors: UsersProfileUpdateError[];
  type: UsersProfileUpdateValidationErrorType;
}
