/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Eternal Anvil (Backend)
 * The backend server for the Eternal Anvil.
 * OpenAPI spec version: v0.0.1
 */
import type { UsersChangePasswordCreateError } from './usersChangePasswordCreateError';
import type { UsersChangePasswordCreateValidationErrorType } from './usersChangePasswordCreateValidationErrorType';

export interface UsersChangePasswordCreateValidationError {
  errors: UsersChangePasswordCreateError[];
  type: UsersChangePasswordCreateValidationErrorType;
}
