/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Eternal Anvil (Backend)
 * The backend server for the Eternal Anvil.
 * OpenAPI spec version: v0.0.1
 */
import type { UsersProfilePartialUpdateUsernameErrorComponentAttr } from './usersProfilePartialUpdateUsernameErrorComponentAttr';
import type { UsersProfilePartialUpdateUsernameErrorComponentCode } from './usersProfilePartialUpdateUsernameErrorComponentCode';

export interface UsersProfilePartialUpdateUsernameErrorComponent {
  attr: UsersProfilePartialUpdateUsernameErrorComponentAttr;
  /** * `blank` - blank
* `invalid` - invalid
* `max_length` - max_length
* `null` - null
* `null_characters_not_allowed` - null_characters_not_allowed
* `required` - required
* `surrogate_characters_not_allowed` - surrogate_characters_not_allowed
* `unique` - unique */
  code: UsersProfilePartialUpdateUsernameErrorComponentCode;
  detail: string;
}
