/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Eternal Anvil (Backend)
 * The backend server for the Eternal Anvil.
 * OpenAPI spec version: v0.0.1
 */
import type { UsersChangePasswordCreate401ErrorsItem } from './usersChangePasswordCreate401ErrorsItem';
import type { UsersChangePasswordCreate401Type } from './usersChangePasswordCreate401Type';

export type UsersChangePasswordCreate401 = {
  errors: UsersChangePasswordCreate401ErrorsItem[];
  type: UsersChangePasswordCreate401Type;
};
