/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Eternal Anvil (Backend)
 * The backend server for the Eternal Anvil.
 * OpenAPI spec version: v0.0.1
 */
import type { UsersRegisterNonFieldErrorsErrorComponentAttr } from './usersRegisterNonFieldErrorsErrorComponentAttr';
import type { UsersRegisterNonFieldErrorsErrorComponentCode } from './usersRegisterNonFieldErrorsErrorComponentCode';

export interface UsersRegisterNonFieldErrorsErrorComponent {
  attr: UsersRegisterNonFieldErrorsErrorComponentAttr;
  /** * `invalid` - invalid
* `null` - null */
  code: UsersRegisterNonFieldErrorsErrorComponentCode;
  detail: string;
}
