/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Eternal Anvil (Backend)
 * The backend server for the Eternal Anvil.
 * OpenAPI spec version: v0.0.1
 */
import type { UsersRegister403ErrorsItem } from './usersRegister403ErrorsItem';
import type { UsersRegister403Type } from './usersRegister403Type';

export type UsersRegister403 = {
  errors: UsersRegister403ErrorsItem[];
  type: UsersRegister403Type;
};
