/**
 * Generated by orval v7.0.1 🍺
 * Do not edit manually.
 * Eternal Anvil (Backend)
 * The backend server for the Eternal Anvil.
 * OpenAPI spec version: v0.0.1
 */

export type UsersRegister403ErrorsItemDetail = typeof UsersRegister403ErrorsItemDetail[keyof typeof UsersRegister403ErrorsItemDetail];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const UsersRegister403ErrorsItemDetail = {
  Registration_is_disabled: 'Registration is disabled.',
} as const;
