/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Eternal Anvil (Backend)
 * The backend server for the Eternal Anvil.
 * OpenAPI spec version: v0.0.1
 */
import type { UsersLoginDiscordCreateNonFieldErrorsErrorComponentAttr } from './usersLoginDiscordCreateNonFieldErrorsErrorComponentAttr';
import type { UsersLoginDiscordCreateNonFieldErrorsErrorComponentCode } from './usersLoginDiscordCreateNonFieldErrorsErrorComponentCode';

export interface UsersLoginDiscordCreateNonFieldErrorsErrorComponent {
  attr: UsersLoginDiscordCreateNonFieldErrorsErrorComponentAttr;
  /** * `invalid` - invalid
* `null` - null */
  code: UsersLoginDiscordCreateNonFieldErrorsErrorComponentCode;
  detail: string;
}
