/**
 * Generated by orval v7.0.1 🍺
 * Do not edit manually.
 * Eternal Anvil (Backend)
 * The backend server for the Eternal Anvil.
 * OpenAPI spec version: v0.0.1
 */
import type { UsersChangePasswordNonFieldErrorsErrorComponentAttr } from './usersChangePasswordNonFieldErrorsErrorComponentAttr';
import type { UsersChangePasswordNonFieldErrorsErrorComponentCode } from './usersChangePasswordNonFieldErrorsErrorComponentCode';

export interface UsersChangePasswordNonFieldErrorsErrorComponent {
  attr: UsersChangePasswordNonFieldErrorsErrorComponentAttr;
  /** * `invalid` - invalid
* `null` - null */
  code: UsersChangePasswordNonFieldErrorsErrorComponentCode;
  detail: string;
}
