/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Eternal Anvil (Backend)
 * The backend server for the Eternal Anvil.
 * OpenAPI spec version: v0.0.1
 */

/**
 * Serializer for change password requests.
 */
export interface UserChangePasswordRequest {
  /** @minLength 1 */
  new_password: string;
  /** @minLength 1 */
  password: string;
}
