/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Eternal Anvil (Backend)
 * The backend server for the Eternal Anvil.
 * OpenAPI spec version: v0.0.1
 */
import type { UsersLoginDiscordCreateError } from './usersLoginDiscordCreateError';
import type { UsersLoginDiscordCreateValidationErrorType } from './usersLoginDiscordCreateValidationErrorType';

export interface UsersLoginDiscordCreateValidationError {
  errors: UsersLoginDiscordCreateError[];
  type: UsersLoginDiscordCreateValidationErrorType;
}
