/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Eternal Anvil (Backend)
 * The backend server for the Eternal Anvil.
 * OpenAPI spec version: v0.0.1
 */
import type { UsersChangePasswordCreateNewPasswordErrorComponent } from './usersChangePasswordCreateNewPasswordErrorComponent';
import type { UsersChangePasswordCreateNonFieldErrorsErrorComponent } from './usersChangePasswordCreateNonFieldErrorsErrorComponent';
import type { UsersChangePasswordCreatePasswordErrorComponent } from './usersChangePasswordCreatePasswordErrorComponent';

export type UsersChangePasswordCreateError = UsersChangePasswordCreateNonFieldErrorsErrorComponent | UsersChangePasswordCreatePasswordErrorComponent | UsersChangePasswordCreateNewPasswordErrorComponent;
