/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Eternal Anvil (Backend)
 * The backend server for the Eternal Anvil.
 * OpenAPI spec version: v0.0.1
 */
import type { UsersRegisterCreateNonFieldErrorsErrorComponent } from './usersRegisterCreateNonFieldErrorsErrorComponent';
import type { UsersRegisterCreatePasswordErrorComponent } from './usersRegisterCreatePasswordErrorComponent';
import type { UsersRegisterCreateUsernameErrorComponent } from './usersRegisterCreateUsernameErrorComponent';

export type UsersRegisterCreateError = UsersRegisterCreateNonFieldErrorsErrorComponent | UsersRegisterCreateUsernameErrorComponent | UsersRegisterCreatePasswordErrorComponent;
