/**
 * Generated by orval v7.0.1 🍺
 * Do not edit manually.
 * Eternal Anvil (Backend)
 * The backend server for the Eternal Anvil.
 * OpenAPI spec version: v0.0.1
 */
import type { UsersLogoutNonFieldErrorsErrorComponentAttr } from './usersLogoutNonFieldErrorsErrorComponentAttr';
import type { UsersLogoutNonFieldErrorsErrorComponentCode } from './usersLogoutNonFieldErrorsErrorComponentCode';

export interface UsersLogoutNonFieldErrorsErrorComponent {
  attr: UsersLogoutNonFieldErrorsErrorComponentAttr;
  /** * `invalid` - invalid
* `null` - null */
  code: UsersLogoutNonFieldErrorsErrorComponentCode;
  detail: string;
}
