/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Eternal Anvil (Backend)
 * The backend server for the Eternal Anvil.
 * OpenAPI spec version: v0.0.1
 */
import type { UsersChangePassword401ErrorsItem } from './usersChangePassword401ErrorsItem';
import type { UsersChangePassword401Type } from './usersChangePassword401Type';

export type UsersChangePassword401 = {
  errors: UsersChangePassword401ErrorsItem[];
  type: UsersChangePassword401Type;
};
