/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Eternal Anvil (Backend)
 * The backend server for the Eternal Anvil.
 * OpenAPI spec version: v0.0.1
 */
import type { UsersLoginRefreshNonFieldErrorsErrorComponentAttr } from './usersLoginRefreshNonFieldErrorsErrorComponentAttr';
import type { UsersLoginRefreshNonFieldErrorsErrorComponentCode } from './usersLoginRefreshNonFieldErrorsErrorComponentCode';

export interface UsersLoginRefreshNonFieldErrorsErrorComponent {
  attr: UsersLoginRefreshNonFieldErrorsErrorComponentAttr;
  /** * `invalid` - invalid
* `null` - null */
  code: UsersLoginRefreshNonFieldErrorsErrorComponentCode;
  detail: string;
}
