/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Eternal Anvil (Backend)
 * The backend server for the Eternal Anvil.
 * OpenAPI spec version: v0.0.1
 */
import type { UsersChangePasswordCreate401ErrorsItemAttr } from './usersChangePasswordCreate401ErrorsItemAttr';
import type { UsersChangePasswordCreate401ErrorsItemCode } from './usersChangePasswordCreate401ErrorsItemCode';
import type { UsersChangePasswordCreate401ErrorsItemDetail } from './usersChangePasswordCreate401ErrorsItemDetail';

export type UsersChangePasswordCreate401ErrorsItem = {
  attr: UsersChangePasswordCreate401ErrorsItemAttr;
  code: UsersChangePasswordCreate401ErrorsItemCode;
  detail: UsersChangePasswordCreate401ErrorsItemDetail;
};
