/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Eternal Anvil (Backend)
 * The backend server for the Eternal Anvil.
 * OpenAPI spec version: v0.0.1
 */

export type UsersRegisterCreate403ErrorsItemAttr = typeof UsersRegisterCreate403ErrorsItemAttr[keyof typeof UsersRegisterCreate403ErrorsItemAttr];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const UsersRegisterCreate403ErrorsItemAttr = {
} as const;
