/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Eternal Anvil (Backend)
 * The backend server for the Eternal Anvil.
 * OpenAPI spec version: v0.0.1
 */
import type { UsersRegisterUsernameErrorComponentAttr } from './usersRegisterUsernameErrorComponentAttr';
import type { UsersRegisterUsernameErrorComponentCode } from './usersRegisterUsernameErrorComponentCode';

export interface UsersRegisterUsernameErrorComponent {
  attr: UsersRegisterUsernameErrorComponentAttr;
  /** * `blank` - blank
* `invalid` - invalid
* `max_length` - max_length
* `null` - null
* `null_characters_not_allowed` - null_characters_not_allowed
* `required` - required
* `surrogate_characters_not_allowed` - surrogate_characters_not_allowed
* `unique` - unique */
  code: UsersRegisterUsernameErrorComponentCode;
  detail: string;
}
