/**
 * Generated by orval v7.0.1 🍺
 * Do not edit manually.
 * Eternal Anvil (Backend)
 * The backend server for the Eternal Anvil.
 * OpenAPI spec version: v0.0.1
 */
import type { UsersProfilePartialUpdateNonFieldErrorsErrorComponent } from './usersProfilePartialUpdateNonFieldErrorsErrorComponent';
import type { UsersProfilePartialUpdateUsernameErrorComponent } from './usersProfilePartialUpdateUsernameErrorComponent';

export type UsersProfilePartialUpdateError = UsersProfilePartialUpdateNonFieldErrorsErrorComponent | UsersProfilePartialUpdateUsernameErrorComponent;
