/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Eternal Anvil (Backend)
 * The backend server for the Eternal Anvil.
 * OpenAPI spec version: v0.0.1
 */
import type { UsersLoginRefreshCreateError } from './usersLoginRefreshCreateError';
import type { UsersLoginRefreshCreateValidationErrorType } from './usersLoginRefreshCreateValidationErrorType';

export interface UsersLoginRefreshCreateValidationError {
  errors: UsersLoginRefreshCreateError[];
  type: UsersLoginRefreshCreateValidationErrorType;
}
