/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Eternal Anvil (Backend)
 * The backend server for the Eternal Anvil.
 * OpenAPI spec version: v0.0.1
 */
import type { UsersLoginCreateNonFieldErrorsErrorComponentAttr } from './usersLoginCreateNonFieldErrorsErrorComponentAttr';
import type { UsersLoginCreateNonFieldErrorsErrorComponentCode } from './usersLoginCreateNonFieldErrorsErrorComponentCode';

export interface UsersLoginCreateNonFieldErrorsErrorComponent {
  attr: UsersLoginCreateNonFieldErrorsErrorComponentAttr;
  /** * `invalid` - invalid
* `no_active_account` - no_active_account
* `null` - null */
  code: UsersLoginCreateNonFieldErrorsErrorComponentCode;
  detail: string;
}
