/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Eternal Anvil (Backend)
 * The backend server for the Eternal Anvil.
 * OpenAPI spec version: v0.0.1
 */
import type { ParseErrorResponse } from './parseErrorResponse';
import type { UsersLoginCreateValidationError } from './usersLoginCreateValidationError';

export type UsersLoginCreateErrorResponse400 = UsersLoginCreateValidationError | ParseErrorResponse;
