/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Eternal Anvil (Backend)
 * The backend server for the Eternal Anvil.
 * OpenAPI spec version: v0.0.1
 */

export type UsersChangePassword401ErrorsItemAttr = typeof UsersChangePassword401ErrorsItemAttr[keyof typeof UsersChangePassword401ErrorsItemAttr];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const UsersChangePassword401ErrorsItemAttr = {
} as const;
