/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Eternal Anvil (Backend)
 * The backend server for the Eternal Anvil.
 * OpenAPI spec version: v0.0.1
 */

export type UsersLoginRefreshCreateValidationErrorType = typeof UsersLoginRefreshCreateValidationErrorType[keyof typeof UsersLoginRefreshCreateValidationErrorType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const UsersLoginRefreshCreateValidationErrorType = {
  validation_error: 'validation_error',
} as const;
