/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Eternal Anvil (Backend)
 * The backend server for the Eternal Anvil.
 * OpenAPI spec version: v0.0.1
 */
import type { UsersChangePasswordCreatePasswordErrorComponentAttr } from './usersChangePasswordCreatePasswordErrorComponentAttr';
import type { UsersChangePasswordCreatePasswordErrorComponentCode } from './usersChangePasswordCreatePasswordErrorComponentCode';

export interface UsersChangePasswordCreatePasswordErrorComponent {
  attr: UsersChangePasswordCreatePasswordErrorComponentAttr;
  /** * `blank` - blank
* `invalid` - invalid
* `null` - null
* `null_characters_not_allowed` - null_characters_not_allowed
* `required` - required
* `surrogate_characters_not_allowed` - surrogate_characters_not_allowed */
  code: UsersChangePasswordCreatePasswordErrorComponentCode;
  detail: string;
}
