/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Eternal Anvil (Backend)
 * The backend server for the Eternal Anvil.
 * OpenAPI spec version: v0.0.1
 */
import type { UsersRegisterCreate403ErrorsItem } from './usersRegisterCreate403ErrorsItem';
import type { UsersRegisterCreate403Type } from './usersRegisterCreate403Type';

export type UsersRegisterCreate403 = {
  errors: UsersRegisterCreate403ErrorsItem[];
  type: UsersRegisterCreate403Type;
};
