/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Eternal Anvil (Backend)
 * The backend server for the Eternal Anvil.
 * OpenAPI spec version: v0.0.1
 */
import type { UsersRegister403ErrorsItemAttr } from './usersRegister403ErrorsItemAttr';
import type { UsersRegister403ErrorsItemCode } from './usersRegister403ErrorsItemCode';
import type { UsersRegister403ErrorsItemDetail } from './usersRegister403ErrorsItemDetail';

export type UsersRegister403ErrorsItem = {
  attr: UsersRegister403ErrorsItemAttr;
  code: UsersRegister403ErrorsItemCode;
  detail: UsersRegister403ErrorsItemDetail;
};
