/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Eternal Anvil (Backend)
 * The backend server for the Eternal Anvil.
 * OpenAPI spec version: v0.0.1
 */

/**
 * * `blank` - blank
* `invalid` - invalid
* `null` - null
* `null_characters_not_allowed` - null_characters_not_allowed
* `required` - required
* `surrogate_characters_not_allowed` - surrogate_characters_not_allowed
 */
export type UsersChangePasswordNewPasswordErrorComponentCode = typeof UsersChangePasswordNewPasswordErrorComponentCode[keyof typeof UsersChangePasswordNewPasswordErrorComponentCode];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const UsersChangePasswordNewPasswordErrorComponentCode = {
  blank: 'blank',
  invalid: 'invalid',
  null: 'null',
  null_characters_not_allowed: 'null_characters_not_allowed',
  required: 'required',
  surrogate_characters_not_allowed: 'surrogate_characters_not_allowed',
} as const;
