/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Eternal Anvil (Backend)
 * The backend server for the Eternal Anvil.
 * OpenAPI spec version: v0.0.1
 */

export interface UserRequest {
  /**
   * @minLength 1
   * @maxLength 255
   */
  username: string;
}
