/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Eternal Anvil (Backend)
 * The backend server for the Eternal Anvil.
 * OpenAPI spec version: v0.0.1
 */
import type { UsersLoginRefreshCreateNonFieldErrorsErrorComponentAttr } from './usersLoginRefreshCreateNonFieldErrorsErrorComponentAttr';
import type { UsersLoginRefreshCreateNonFieldErrorsErrorComponentCode } from './usersLoginRefreshCreateNonFieldErrorsErrorComponentCode';

export interface UsersLoginRefreshCreateNonFieldErrorsErrorComponent {
  attr: UsersLoginRefreshCreateNonFieldErrorsErrorComponentAttr;
  /** * `invalid` - invalid
* `null` - null */
  code: UsersLoginRefreshCreateNonFieldErrorsErrorComponentCode;
  detail: string;
}
