/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Eternal Anvil (Backend)
 * The backend server for the Eternal Anvil.
 * OpenAPI spec version: v0.0.1
 */

export type UsersLoginDiscordCreateCodeErrorComponentAttr = typeof UsersLoginDiscordCreateCodeErrorComponentAttr[keyof typeof UsersLoginDiscordCreateCodeErrorComponentAttr];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const UsersLoginDiscordCreateCodeErrorComponentAttr = {
  code: 'code',
} as const;
