/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Eternal Anvil (Backend)
 * The backend server for the Eternal Anvil.
 * OpenAPI spec version: v0.0.1
 */
import type { UsersLoginNonFieldErrorsErrorComponent } from './usersLoginNonFieldErrorsErrorComponent';
import type { UsersLoginPasswordErrorComponent } from './usersLoginPasswordErrorComponent';
import type { UsersLoginUsernameErrorComponent } from './usersLoginUsernameErrorComponent';

export type UsersLoginError = UsersLoginNonFieldErrorsErrorComponent | UsersLoginUsernameErrorComponent | UsersLoginPasswordErrorComponent;
