/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Eternal Anvil (Backend)
 * The backend server for the Eternal Anvil.
 * OpenAPI spec version: v0.0.1
 */

export type UsersRegisterCreate403ErrorsItemDetail = typeof UsersRegisterCreate403ErrorsItemDetail[keyof typeof UsersRegisterCreate403ErrorsItemDetail];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const UsersRegisterCreate403ErrorsItemDetail = {
  Registration_is_disabled: 'Registration is disabled.',
} as const;
