/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Eternal Anvil (Backend)
 * The backend server for the Eternal Anvil.
 * OpenAPI spec version: v0.0.1
 */
import type { UsersRegisterCreateNonFieldErrorsErrorComponentAttr } from './usersRegisterCreateNonFieldErrorsErrorComponentAttr';
import type { UsersRegisterCreateNonFieldErrorsErrorComponentCode } from './usersRegisterCreateNonFieldErrorsErrorComponentCode';

export interface UsersRegisterCreateNonFieldErrorsErrorComponent {
  attr: UsersRegisterCreateNonFieldErrorsErrorComponentAttr;
  /** * `invalid` - invalid
* `null` - null */
  code: UsersRegisterCreateNonFieldErrorsErrorComponentCode;
  detail: string;
}
