/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Eternal Anvil (Backend)
 * The backend server for the Eternal Anvil.
 * OpenAPI spec version: v0.0.1
 */

/**
 * * `invalid` - invalid
* `no_active_account` - no_active_account
* `null` - null
 */
export type UsersLoginCreateNonFieldErrorsErrorComponentCode = typeof UsersLoginCreateNonFieldErrorsErrorComponentCode[keyof typeof UsersLoginCreateNonFieldErrorsErrorComponentCode];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const UsersLoginCreateNonFieldErrorsErrorComponentCode = {
  invalid: 'invalid',
  no_active_account: 'no_active_account',
  null: 'null',
} as const;
