/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Eternal Anvil (Backend)
 * The backend server for the Eternal Anvil.
 * OpenAPI spec version: v0.0.1
 */

export type UsersLoginDiscordCreateValidationErrorType = typeof UsersLoginDiscordCreateValidationErrorType[keyof typeof UsersLoginDiscordCreateValidationErrorType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const UsersLoginDiscordCreateValidationErrorType = {
  validation_error: 'validation_error',
} as const;
