/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Eternal Anvil (Backend)
 * The backend server for the Eternal Anvil.
 * OpenAPI spec version: v0.0.1
 */
import type { UsersLogoutCreateError } from './usersLogoutCreateError';
import type { UsersLogoutCreateValidationErrorType } from './usersLogoutCreateValidationErrorType';

export interface UsersLogoutCreateValidationError {
  errors: UsersLogoutCreateError[];
  type: UsersLogoutCreateValidationErrorType;
}
