/**
 * Generated by orval v7.0.1 🍺
 * Do not edit manually.
 * Eternal Anvil (Backend)
 * The backend server for the Eternal Anvil.
 * OpenAPI spec version: v0.0.1
 */
import type { UsersProfilePartialUpdateNonFieldErrorsErrorComponentAttr } from './usersProfilePartialUpdateNonFieldErrorsErrorComponentAttr';
import type { UsersProfilePartialUpdateNonFieldErrorsErrorComponentCode } from './usersProfilePartialUpdateNonFieldErrorsErrorComponentCode';

export interface UsersProfilePartialUpdateNonFieldErrorsErrorComponent {
  attr: UsersProfilePartialUpdateNonFieldErrorsErrorComponentAttr;
  /** * `invalid` - invalid
* `null` - null */
  code: UsersProfilePartialUpdateNonFieldErrorsErrorComponentCode;
  detail: string;
}
