/**
 * Generated by orval v7.0.1 🍺
 * Do not edit manually.
 * Eternal Anvil (Backend)
 * The backend server for the Eternal Anvil.
 * OpenAPI spec version: v0.0.1
 */

export type UsersChangePassword401ErrorsItemCode = typeof UsersChangePassword401ErrorsItemCode[keyof typeof UsersChangePassword401ErrorsItemCode];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const UsersChangePassword401ErrorsItemCode = {
  authentication_failed: 'authentication_failed',
} as const;
