/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Eternal Anvil (Backend)
 * The backend server for the Eternal Anvil.
 * OpenAPI spec version: v0.0.1
 */
import type { UsersChangePasswordCreateNonFieldErrorsErrorComponentAttr } from './usersChangePasswordCreateNonFieldErrorsErrorComponentAttr';
import type { UsersChangePasswordCreateNonFieldErrorsErrorComponentCode } from './usersChangePasswordCreateNonFieldErrorsErrorComponentCode';

export interface UsersChangePasswordCreateNonFieldErrorsErrorComponent {
  attr: UsersChangePasswordCreateNonFieldErrorsErrorComponentAttr;
  /** * `invalid` - invalid
* `null` - null */
  code: UsersChangePasswordCreateNonFieldErrorsErrorComponentCode;
  detail: string;
}
