/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Eternal Anvil (Backend)
 * The backend server for the Eternal Anvil.
 * OpenAPI spec version: v0.0.1
 */

export type UsersChangePasswordCreate401ErrorsItemAttr = typeof UsersChangePasswordCreate401ErrorsItemAttr[keyof typeof UsersChangePasswordCreate401ErrorsItemAttr];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const UsersChangePasswordCreate401ErrorsItemAttr = {
} as const;
