/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Eternal Anvil (Backend)
 * The backend server for the Eternal Anvil.
 * OpenAPI spec version: v0.0.1
 */
import type { UsersLogoutCreateNonFieldErrorsErrorComponentAttr } from './usersLogoutCreateNonFieldErrorsErrorComponentAttr';
import type { UsersLogoutCreateNonFieldErrorsErrorComponentCode } from './usersLogoutCreateNonFieldErrorsErrorComponentCode';

export interface UsersLogoutCreateNonFieldErrorsErrorComponent {
  attr: UsersLogoutCreateNonFieldErrorsErrorComponentAttr;
  /** * `invalid` - invalid
* `null` - null */
  code: UsersLogoutCreateNonFieldErrorsErrorComponentCode;
  detail: string;
}
