/**
 * Generated by orval v7.0.1 🍺
 * Do not edit manually.
 * Eternal Anvil (Backend)
 * The backend server for the Eternal Anvil.
 * OpenAPI spec version: v0.0.1
 */

/**
 * Serializer for retrieving the current user's `USERNAME_FIELD` data (usually username or email).
 */
export interface UserWhoami {
  /** @maxLength 255 */
  username: string;
}
