/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Eternal Anvil (Backend)
 * The backend server for the Eternal Anvil.
 * OpenAPI spec version: v0.0.1
 */
import type { UsersRegisterError } from './usersRegisterError';
import type { UsersRegisterValidationErrorType } from './usersRegisterValidationErrorType';

export interface UsersRegisterValidationError {
  errors: UsersRegisterError[];
  type: UsersRegisterValidationErrorType;
}
