/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Eternal Anvil (Backend)
 * The backend server for the Eternal Anvil.
 * OpenAPI spec version: v0.0.1
 */

export type UsersProfileUpdateValidationErrorType = typeof UsersProfileUpdateValidationErrorType[keyof typeof UsersProfileUpdateValidationErrorType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const UsersProfileUpdateValidationErrorType = {
  validation_error: 'validation_error',
} as const;
