/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Eternal Anvil (Backend)
 * The backend server for the Eternal Anvil.
 * OpenAPI spec version: v0.0.1
 */

/**
 * * `validation_error` - Validation Error
 */
export type ValidationErrorEnum = typeof ValidationErrorEnum[keyof typeof ValidationErrorEnum];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ValidationErrorEnum = {
  validation_error: 'validation_error',
} as const;
