name: Build and Push Docker Image

on:
  push:
    branches:
      - '**'
    tags:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Extract branch or tag name
      id: extract_ref
      run: |
        if [[ "${{ github.ref }}" == refs/heads/* ]]; then
          echo "ref_type=branch" >> $GITHUB_ENV
          echo "ref_name=${{ github.ref }}" | sed 's#refs/heads/##' >> $GITHUB_ENV
        elif [[ "${{ github.ref }}" == refs/tags/* ]]; then
          echo "ref_type=tag" >> $GITHUB_ENV
          echo "ref_name=${{ github.ref }}" | sed 's#refs/tags/##' >> $GITHUB_ENV
        fi

    - name: Extract repository name
      id: extract_repo
      run: echo "repo_name=${{ github.repository }}" | awk -F '/' '{print $2}' >> $GITHUB_ENV

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: ghcr.io/${{ github.repository_owner }}/${{ env.repo_name }}:${{ env.ref_name }}

    - name: Logout from GitHub Container Registry
      run: docker logout ghcr.io
